//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroInstall.Commands.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ZeroInstall.Commands.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Added0installToPath {
            get {
                return ResourceManager.GetString("Added0installToPath", resourceCulture);
            }
        }
        
        public static string AliasCreated {
            get {
                return ResourceManager.GetString("AliasCreated", resourceCulture);
            }
        }
        
        public static string AliasNotFound {
            get {
                return ResourceManager.GetString("AliasNotFound", resourceCulture);
            }
        }
        
        public static string AliasRemoved {
            get {
                return ResourceManager.GetString("AliasRemoved", resourceCulture);
            }
        }
        
        public static string AllComponentsDownloaded {
            get {
                return ResourceManager.GetString("AllComponentsDownloaded", resourceCulture);
            }
        }
        
        public static string AllComponentsExported {
            get {
                return ResourceManager.GetString("AllComponentsExported", resourceCulture);
            }
        }
        
        public static string AlreadyInImplDirs {
            get {
                return ResourceManager.GetString("AlreadyInImplDirs", resourceCulture);
            }
        }
        
        public static string AppAlias {
            get {
                return ResourceManager.GetString("AppAlias", resourceCulture);
            }
        }
        
        public static string AppList {
            get {
                return ResourceManager.GetString("AppList", resourceCulture);
            }
        }
        
        public static string AskDeployMachineWide {
            get {
                return ResourceManager.GetString("AskDeployMachineWide", resourceCulture);
            }
        }
        
        public static string AskDeployNewTarget {
            get {
                return ResourceManager.GetString("AskDeployNewTarget", resourceCulture);
            }
        }
        
        public static string AskDeployZeroInstall {
            get {
                return ResourceManager.GetString("AskDeployZeroInstall", resourceCulture);
            }
        }
        
        public static string AskRemoveZeroInstall {
            get {
                return ResourceManager.GetString("AskRemoveZeroInstall", resourceCulture);
            }
        }
        
        public static string AskTryNow {
            get {
                return ResourceManager.GetString("AskTryNow", resourceCulture);
            }
        }
        
        public static string AskUpdateCapabilities {
            get {
                return ResourceManager.GetString("AskUpdateCapabilities", resourceCulture);
            }
        }
        
        public static string CachedImplementations {
            get {
                return ResourceManager.GetString("CachedImplementations", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string CapabilitiesChanged {
            get {
                return ResourceManager.GetString("CapabilitiesChanged", resourceCulture);
            }
        }
        
        public static string CatalogAlreadyRegistered {
            get {
                return ResourceManager.GetString("CatalogAlreadyRegistered", resourceCulture);
            }
        }
        
        public static string CatalogNotRegistered {
            get {
                return ResourceManager.GetString("CatalogNotRegistered", resourceCulture);
            }
        }
        
        public static string CatalogSources {
            get {
                return ResourceManager.GetString("CatalogSources", resourceCulture);
            }
        }
        
        public static string CannotUseOptionsTogether {
            get {
                return ResourceManager.GetString("CannotUseOptionsTogether", resourceCulture);
            }
        }
        
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        public static string ChangesFound {
            get {
                return ResourceManager.GetString("ChangesFound", resourceCulture);
            }
        }
        
        public static string CheckingFeed {
            get {
                return ResourceManager.GetString("CheckingFeed", resourceCulture);
            }
        }
        
        public static string CheckingForUpdates {
            get {
                return ResourceManager.GetString("CheckingForUpdates", resourceCulture);
            }
        }
        
        public static string ClickToChoose {
            get {
                return ResourceManager.GetString("ClickToChoose", resourceCulture);
            }
        }
        
        public static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        public static string CommandLineArguments {
            get {
                return ResourceManager.GetString("CommandLineArguments", resourceCulture);
            }
        }
        
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        public static string ConfirmPurge {
            get {
                return ResourceManager.GetString("ConfirmPurge", resourceCulture);
            }
        }
        
        public static string ConfirmRemoveAll {
            get {
                return ResourceManager.GetString("ConfirmRemoveAll", resourceCulture);
            }
        }
        
        public static string DataGridCommandAccessPointHelp {
            get {
                return ResourceManager.GetString("DataGridCommandAccessPointHelp", resourceCulture);
            }
        }
        
        public static string DataGridDefaultAccessPointHelp {
            get {
                return ResourceManager.GetString("DataGridDefaultAccessPointHelp", resourceCulture);
            }
        }
        
        public static string DeleteCheckedEntries {
            get {
                return ResourceManager.GetString("DeleteCheckedEntries", resourceCulture);
            }
        }
        
        public static string DeleteEntry {
            get {
                return ResourceManager.GetString("DeleteEntry", resourceCulture);
            }
        }
        
        public static string DeletingImplementations {
            get {
                return ResourceManager.GetString("DeletingImplementations", resourceCulture);
            }
        }
        
        public static string DeployedPortable {
            get {
                return ResourceManager.GetString("DeployedPortable", resourceCulture);
            }
        }
        
        public static string DeployMissingTargetForPortable {
            get {
                return ResourceManager.GetString("DeployMissingTargetForPortable", resourceCulture);
            }
        }
        
        public static string DeployTargetOutsideHome {
            get {
                return ResourceManager.GetString("DeployTargetOutsideHome", resourceCulture);
            }
        }
        
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        public static string DescriptionAddAlias {
            get {
                return ResourceManager.GetString("DescriptionAddAlias", resourceCulture);
            }
        }
        
        public static string DescriptionAddApp {
            get {
                return ResourceManager.GetString("DescriptionAddApp", resourceCulture);
            }
        }
        
        public static string DescriptionAddFeed {
            get {
                return ResourceManager.GetString("DescriptionAddFeed", resourceCulture);
            }
        }
        
        public static string DescriptionCatalogAdd {
            get {
                return ResourceManager.GetString("DescriptionCatalogAdd", resourceCulture);
            }
        }
        
        public static string DescriptionCatalogList {
            get {
                return ResourceManager.GetString("DescriptionCatalogList", resourceCulture);
            }
        }
        
        public static string DescriptionCatalogRefresh {
            get {
                return ResourceManager.GetString("DescriptionCatalogRefresh", resourceCulture);
            }
        }
        
        public static string DescriptionCatalogRemove {
            get {
                return ResourceManager.GetString("DescriptionCatalogRemove", resourceCulture);
            }
        }
        
        public static string DescriptionCatalogReset {
            get {
                return ResourceManager.GetString("DescriptionCatalogReset", resourceCulture);
            }
        }
        
        public static string DescriptionCatalogSearch {
            get {
                return ResourceManager.GetString("DescriptionCatalogSearch", resourceCulture);
            }
        }
        
        public static string DescriptionCentral {
            get {
                return ResourceManager.GetString("DescriptionCentral", resourceCulture);
            }
        }
        
        public static string DescriptionConfig {
            get {
                return ResourceManager.GetString("DescriptionConfig", resourceCulture);
            }
        }
        
        public static string DescriptionDigest {
            get {
                return ResourceManager.GetString("DescriptionDigest", resourceCulture);
            }
        }
        
        public static string DescriptionDownload {
            get {
                return ResourceManager.GetString("DescriptionDownload", resourceCulture);
            }
        }
        
        public static string DescriptionExport {
            get {
                return ResourceManager.GetString("DescriptionExport", resourceCulture);
            }
        }
        
        public static string DescriptionImport {
            get {
                return ResourceManager.GetString("DescriptionImport", resourceCulture);
            }
        }
        
        public static string DescriptionImportApps {
            get {
                return ResourceManager.GetString("DescriptionImportApps", resourceCulture);
            }
        }
        
        public static string DescriptionIntegrateApp {
            get {
                return ResourceManager.GetString("DescriptionIntegrateApp", resourceCulture);
            }
        }
        
        public static string DescriptionList {
            get {
                return ResourceManager.GetString("DescriptionList", resourceCulture);
            }
        }
        
        public static string DescriptionListApps {
            get {
                return ResourceManager.GetString("DescriptionListApps", resourceCulture);
            }
        }
        
        public static string DescriptionListFeeds {
            get {
                return ResourceManager.GetString("DescriptionListFeeds", resourceCulture);
            }
        }
        
        public static string DescriptionMaintenanceDeploy {
            get {
                return ResourceManager.GetString("DescriptionMaintenanceDeploy", resourceCulture);
            }
        }
        
        public static string DescriptionMaintenanceRemove {
            get {
                return ResourceManager.GetString("DescriptionMaintenanceRemove", resourceCulture);
            }
        }
        
        public static string DescriptionRemoveAllApps {
            get {
                return ResourceManager.GetString("DescriptionRemoveAllApps", resourceCulture);
            }
        }
        
        public static string DescriptionRemoveApp {
            get {
                return ResourceManager.GetString("DescriptionRemoveApp", resourceCulture);
            }
        }
        
        public static string DescriptionRemoveFeed {
            get {
                return ResourceManager.GetString("DescriptionRemoveFeed", resourceCulture);
            }
        }
        
        public static string DescriptionRepairApps {
            get {
                return ResourceManager.GetString("DescriptionRepairApps", resourceCulture);
            }
        }
        
        public static string DescriptionRun {
            get {
                return ResourceManager.GetString("DescriptionRun", resourceCulture);
            }
        }
        
        public static string DescriptionSearch {
            get {
                return ResourceManager.GetString("DescriptionSearch", resourceCulture);
            }
        }
        
        public static string DescriptionSelect {
            get {
                return ResourceManager.GetString("DescriptionSelect", resourceCulture);
            }
        }
        
        public static string DescriptionSelfUpdate {
            get {
                return ResourceManager.GetString("DescriptionSelfUpdate", resourceCulture);
            }
        }
        
        public static string DescriptionStoreAdd {
            get {
                return ResourceManager.GetString("DescriptionStoreAdd", resourceCulture);
            }
        }
        
        public static string DescriptionStoreAddDir {
            get {
                return ResourceManager.GetString("DescriptionStoreAddDir", resourceCulture);
            }
        }
        
        public static string DescriptionStoreAudit {
            get {
                return ResourceManager.GetString("DescriptionStoreAudit", resourceCulture);
            }
        }
        
        public static string DescriptionStoreCopy {
            get {
                return ResourceManager.GetString("DescriptionStoreCopy", resourceCulture);
            }
        }
        
        public static string DescriptionStoreExport {
            get {
                return ResourceManager.GetString("DescriptionStoreExport", resourceCulture);
            }
        }
        
        public static string DescriptionStoreFind {
            get {
                return ResourceManager.GetString("DescriptionStoreFind", resourceCulture);
            }
        }
        
        public static string DescriptionStoreList {
            get {
                return ResourceManager.GetString("DescriptionStoreList", resourceCulture);
            }
        }
        
        public static string DescriptionStoreListImplementations {
            get {
                return ResourceManager.GetString("DescriptionStoreListImplementations", resourceCulture);
            }
        }
        
        public static string DescriptionStoreManage {
            get {
                return ResourceManager.GetString("DescriptionStoreManage", resourceCulture);
            }
        }
        
        public static string DescriptionStoreOptimise {
            get {
                return ResourceManager.GetString("DescriptionStoreOptimise", resourceCulture);
            }
        }
        
        public static string DescriptionStorePurge {
            get {
                return ResourceManager.GetString("DescriptionStorePurge", resourceCulture);
            }
        }
        
        public static string DescriptionStoreRemove {
            get {
                return ResourceManager.GetString("DescriptionStoreRemove", resourceCulture);
            }
        }
        
        public static string DescriptionStoreRemoveDir {
            get {
                return ResourceManager.GetString("DescriptionStoreRemoveDir", resourceCulture);
            }
        }
        
        public static string DescriptionStoreVerify {
            get {
                return ResourceManager.GetString("DescriptionStoreVerify", resourceCulture);
            }
        }
        
        public static string DescriptionSync {
            get {
                return ResourceManager.GetString("DescriptionSync", resourceCulture);
            }
        }
        
        public static string DescriptionUpdate {
            get {
                return ResourceManager.GetString("DescriptionUpdate", resourceCulture);
            }
        }
        
        public static string DescriptionUpdateApps {
            get {
                return ResourceManager.GetString("DescriptionUpdateApps", resourceCulture);
            }
        }
        
        public static string DesktopIntegration {
            get {
                return ResourceManager.GetString("DesktopIntegration", resourceCulture);
            }
        }
        
        public static string DesktopIntegrationApply {
            get {
                return ResourceManager.GetString("DesktopIntegrationApply", resourceCulture);
            }
        }
        
        public static string DesktopIntegrationRemove {
            get {
                return ResourceManager.GetString("DesktopIntegrationRemove", resourceCulture);
            }
        }
        
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        public static string DownloadComplete {
            get {
                return ResourceManager.GetString("DownloadComplete", resourceCulture);
            }
        }
        
        public static string EnterCatalogUrl {
            get {
                return ResourceManager.GetString("EnterCatalogUrl", resourceCulture);
            }
        }
        
        public static string EnterFeedUrl {
            get {
                return ResourceManager.GetString("EnterFeedUrl", resourceCulture);
            }
        }
        
        public static string ExclusiveOptions {
            get {
                return ResourceManager.GetString("ExclusiveOptions", resourceCulture);
            }
        }
        
        public static string ExistingInstance {
            get {
                return ResourceManager.GetString("ExistingInstance", resourceCulture);
            }
        }
        
        public static string ExportComplete {
            get {
                return ResourceManager.GetString("ExportComplete", resourceCulture);
            }
        }
        
        public static string FeedAlreadyRegistered {
            get {
                return ResourceManager.GetString("FeedAlreadyRegistered", resourceCulture);
            }
        }
        
        public static string FeedManagement {
            get {
                return ResourceManager.GetString("FeedManagement", resourceCulture);
            }
        }
        
        public static string FeedNotRegistered {
            get {
                return ResourceManager.GetString("FeedNotRegistered", resourceCulture);
            }
        }
        
        public static string FeedRegistered {
            get {
                return ResourceManager.GetString("FeedRegistered", resourceCulture);
            }
        }
        
        public static string FeedReplaced {
            get {
                return ResourceManager.GetString("FeedReplaced", resourceCulture);
            }
        }
        
        public static string FeedReplacedAsk {
            get {
                return ResourceManager.GetString("FeedReplacedAsk", resourceCulture);
            }
        }
        
        public static string FeedsCached {
            get {
                return ResourceManager.GetString("FeedsCached", resourceCulture);
            }
        }
        
        public static string FeedsRegistered {
            get {
                return ResourceManager.GetString("FeedsRegistered", resourceCulture);
            }
        }
        
        public static string FeedUnregistered {
            get {
                return ResourceManager.GetString("FeedUnregistered", resourceCulture);
            }
        }
        
        public static string FileOrDirNotFound {
            get {
                return ResourceManager.GetString("FileOrDirNotFound", resourceCulture);
            }
        }
        
        public static string FilePrefixAbsoluteUsage {
            get {
                return ResourceManager.GetString("FilePrefixAbsoluteUsage", resourceCulture);
            }
        }
        
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        public static string IgnoreMissingFeedFor {
            get {
                return ResourceManager.GetString("IgnoreMissingFeedFor", resourceCulture);
            }
        }
        
        public static string InstallService {
            get {
                return ResourceManager.GetString("InstallService", resourceCulture);
            }
        }
        
        public static string Integrate {
            get {
                return ResourceManager.GetString("Integrate", resourceCulture);
            }
        }
        
        public static string IntegrateAppInvalid {
            get {
                return ResourceManager.GetString("IntegrateAppInvalid", resourceCulture);
            }
        }
        
        public static string IntegrateAppRetry {
            get {
                return ResourceManager.GetString("IntegrateAppRetry", resourceCulture);
            }
        }
        
        public static string IntegrateAppUseGui {
            get {
                return ResourceManager.GetString("IntegrateAppUseGui", resourceCulture);
            }
        }
        
        public static string InvalidArgument {
            get {
                return ResourceManager.GetString("InvalidArgument", resourceCulture);
            }
        }
        
        public static string LicenseInfo {
            get {
                return ResourceManager.GetString("LicenseInfo", resourceCulture);
            }
        }
        
        public static string LocalPathOf {
            get {
                return ResourceManager.GetString("LocalPathOf", resourceCulture);
            }
        }
        
        public static string MissingArguments {
            get {
                return ResourceManager.GetString("MissingArguments", resourceCulture);
            }
        }
        
        public static string MissingFeedFor {
            get {
                return ResourceManager.GetString("MissingFeedFor", resourceCulture);
            }
        }
        
        public static string MissingOptionValue {
            get {
                return ResourceManager.GetString("MissingOptionValue", resourceCulture);
            }
        }
        
        public static string MustBeAdminForMachineWide {
            get {
                return ResourceManager.GetString("MustBeAdminForMachineWide", resourceCulture);
            }
        }
        
        public static string MutexWait {
            get {
                return ResourceManager.GetString("MutexWait", resourceCulture);
            }
        }
        
        public static string MyApps {
            get {
                return ResourceManager.GetString("MyApps", resourceCulture);
            }
        }
        
        public static string NeedsGui {
            get {
                return ResourceManager.GetString("NeedsGui", resourceCulture);
            }
        }
        
        public static string NoAddCommandWithoutAlias {
            get {
                return ResourceManager.GetString("NoAddCommandWithoutAlias", resourceCulture);
            }
        }
        
        public static string NoCustomizeSelectionsInCli {
            get {
                return ResourceManager.GetString("NoCustomizeSelectionsInCli", resourceCulture);
            }
        }
        
        public static string NoIntegrationFromCache {
            get {
                return ResourceManager.GetString("NoIntegrationFromCache", resourceCulture);
            }
        }
        
        public static string NoIntegrationFromPortable {
            get {
                return ResourceManager.GetString("NoIntegrationFromPortable", resourceCulture);
            }
        }
        
        public static string NoMachineWideIntegrationFromPerUser {
            get {
                return ResourceManager.GetString("NoMachineWideIntegrationFromPerUser", resourceCulture);
            }
        }
        
        public static string NoRunWithEmptyCommand {
            get {
                return ResourceManager.GetString("NoRunWithEmptyCommand", resourceCulture);
            }
        }
        
        public static string NoSelectionsDocumentUpdate {
            get {
                return ResourceManager.GetString("NoSelectionsDocumentUpdate", resourceCulture);
            }
        }
        
        public static string NotAvailableInPortableMode {
            get {
                return ResourceManager.GetString("NotAvailableInPortableMode", resourceCulture);
            }
        }
        
        public static string NotInImplDirs {
            get {
                return ResourceManager.GetString("NotInImplDirs", resourceCulture);
            }
        }
        
        public static string NoUpdatesFound {
            get {
                return ResourceManager.GetString("NoUpdatesFound", resourceCulture);
            }
        }
        
        public static string OpenInFileManager {
            get {
                return ResourceManager.GetString("OpenInFileManager", resourceCulture);
            }
        }
        
        public static string OptimiseComplete {
            get {
                return ResourceManager.GetString("OptimiseComplete", resourceCulture);
            }
        }
        
        public static string OptionAlgorithm {
            get {
                return ResourceManager.GetString("OptionAlgorithm", resourceCulture);
            }
        }
        
        public static string OptionAliasRemove {
            get {
                return ResourceManager.GetString("OptionAliasRemove", resourceCulture);
            }
        }
        
        public static string OptionAliasResolve {
            get {
                return ResourceManager.GetString("OptionAliasResolve", resourceCulture);
            }
        }
        
        public static string OptionBackground {
            get {
                return ResourceManager.GetString("OptionBackground", resourceCulture);
            }
        }
        
        public static string OptionBatch {
            get {
                return ResourceManager.GetString("OptionBatch", resourceCulture);
            }
        }
        
        public static string OptionBefore {
            get {
                return ResourceManager.GetString("OptionBefore", resourceCulture);
            }
        }
        
        public static string OptionCatalogAddSkipVerify {
            get {
                return ResourceManager.GetString("OptionCatalogAddSkipVerify", resourceCulture);
            }
        }
        
        public static string OptionClean {
            get {
                return ResourceManager.GetString("OptionClean", resourceCulture);
            }
        }
        
        public static string OptionCommand {
            get {
                return ResourceManager.GetString("OptionCommand", resourceCulture);
            }
        }
        
        public static string OptionConfigTab {
            get {
                return ResourceManager.GetString("OptionConfigTab", resourceCulture);
            }
        }
        
        public static string OptionCpu {
            get {
                return ResourceManager.GetString("OptionCpu", resourceCulture);
            }
        }
        
        public static string OptionCustomize {
            get {
                return ResourceManager.GetString("OptionCustomize", resourceCulture);
            }
        }
        
        public static string OptionDigest {
            get {
                return ResourceManager.GetString("OptionDigest", resourceCulture);
            }
        }
        
        public static string OptionExportBootstrap {
            get {
                return ResourceManager.GetString("OptionExportBootstrap", resourceCulture);
            }
        }
        
        public static string OptionExportIncludeZeroInstall {
            get {
                return ResourceManager.GetString("OptionExportIncludeZeroInstall", resourceCulture);
            }
        }
        
        public static string OptionExportNoImplementations {
            get {
                return ResourceManager.GetString("OptionExportNoImplementations", resourceCulture);
            }
        }
        
        public static string OptionForceSelfUpdate {
            get {
                return ResourceManager.GetString("OptionForceSelfUpdate", resourceCulture);
            }
        }
        
        public static string OptionHelp {
            get {
                return ResourceManager.GetString("OptionHelp", resourceCulture);
            }
        }
        
        public static string OptionIntegrateAdd {
            get {
                return ResourceManager.GetString("OptionIntegrateAdd", resourceCulture);
            }
        }
        
        public static string OptionIntegrateAddAll {
            get {
                return ResourceManager.GetString("OptionIntegrateAddAll", resourceCulture);
            }
        }
        
        public static string OptionIntegrateAddStandard {
            get {
                return ResourceManager.GetString("OptionIntegrateAddStandard", resourceCulture);
            }
        }
        
        public static string OptionIntegrateRemove {
            get {
                return ResourceManager.GetString("OptionIntegrateRemove", resourceCulture);
            }
        }
        
        public static string OptionIntegrateRemoveAll {
            get {
                return ResourceManager.GetString("OptionIntegrateRemoveAll", resourceCulture);
            }
        }
        
        public static string OptionLanguage {
            get {
                return ResourceManager.GetString("OptionLanguage", resourceCulture);
            }
        }
        
        public static string OptionLibrary {
            get {
                return ResourceManager.GetString("OptionLibrary", resourceCulture);
            }
        }
        
        public static string OptionMachine {
            get {
                return ResourceManager.GetString("OptionMachine", resourceCulture);
            }
        }
        
        public static string OptionMain {
            get {
                return ResourceManager.GetString("OptionMain", resourceCulture);
            }
        }
        
        public static string OptionMan {
            get {
                return ResourceManager.GetString("OptionMan", resourceCulture);
            }
        }
        
        public static string OptionManifest {
            get {
                return ResourceManager.GetString("OptionManifest", resourceCulture);
            }
        }
        
        public static string OptionNoDownload {
            get {
                return ResourceManager.GetString("OptionNoDownload", resourceCulture);
            }
        }
        
        public static string OptionNotBefore {
            get {
                return ResourceManager.GetString("OptionNotBefore", resourceCulture);
            }
        }
        
        public static string OptionNoWait {
            get {
                return ResourceManager.GetString("OptionNoWait", resourceCulture);
            }
        }
        
        public static string OptionOffline {
            get {
                return ResourceManager.GetString("OptionOffline", resourceCulture);
            }
        }
        
        public static string OptionOS {
            get {
                return ResourceManager.GetString("OptionOS", resourceCulture);
            }
        }
        
        public static string OptionPortable {
            get {
                return ResourceManager.GetString("OptionPortable", resourceCulture);
            }
        }
        
        public static string OptionRefresh {
            get {
                return ResourceManager.GetString("OptionRefresh", resourceCulture);
            }
        }
        
        public static string OptionRestartCentral {
            get {
                return ResourceManager.GetString("OptionRestartCentral", resourceCulture);
            }
        }
        
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        public static string OptionShow {
            get {
                return ResourceManager.GetString("OptionShow", resourceCulture);
            }
        }
        
        public static string OptionSource {
            get {
                return ResourceManager.GetString("OptionSource", resourceCulture);
            }
        }
        
        public static string OptionSyncReset {
            get {
                return ResourceManager.GetString("OptionSyncReset", resourceCulture);
            }
        }
        
        public static string OptionVerbose {
            get {
                return ResourceManager.GetString("OptionVerbose", resourceCulture);
            }
        }
        
        public static string OptionVersion {
            get {
                return ResourceManager.GetString("OptionVersion", resourceCulture);
            }
        }
        
        public static string OptionVersionRange {
            get {
                return ResourceManager.GetString("OptionVersionRange", resourceCulture);
            }
        }
        
        public static string OptionVersionRangeFor {
            get {
                return ResourceManager.GetString("OptionVersionRangeFor", resourceCulture);
            }
        }
        
        public static string OptionWithStore {
            get {
                return ResourceManager.GetString("OptionWithStore", resourceCulture);
            }
        }
        
        public static string OptionWrapper {
            get {
                return ResourceManager.GetString("OptionWrapper", resourceCulture);
            }
        }
        
        public static string OptionXml {
            get {
                return ResourceManager.GetString("OptionXml", resourceCulture);
            }
        }
        
        public static string PortableMode {
            get {
                return ResourceManager.GetString("PortableMode", resourceCulture);
            }
        }
        
        public static string PropertiesFor {
            get {
                return ResourceManager.GetString("PropertiesFor", resourceCulture);
            }
        }
        
        public static string ReadingCache {
            get {
                return ResourceManager.GetString("ReadingCache", resourceCulture);
            }
        }
        
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        public static string RemoveCheckedKeys {
            get {
                return ResourceManager.GetString("RemoveCheckedKeys", resourceCulture);
            }
        }
        
        public static string RemoveSelectedEntries {
            get {
                return ResourceManager.GetString("RemoveSelectedEntries", resourceCulture);
            }
        }
        
        public static string RemovingApplications {
            get {
                return ResourceManager.GetString("RemovingApplications", resourceCulture);
            }
        }
        
        public static string RemovingOutdated {
            get {
                return ResourceManager.GetString("RemovingOutdated", resourceCulture);
            }
        }
        
        public static string ReopenTerminal {
            get {
                return ResourceManager.GetString("ReopenTerminal", resourceCulture);
            }
        }
        
        public static string ResetList {
            get {
                return ResourceManager.GetString("ResetList", resourceCulture);
            }
        }
        
        public static string ResolvedUsingAlias {
            get {
                return ResourceManager.GetString("ResolvedUsingAlias", resourceCulture);
            }
        }
        
        public static string ResolvedUsingCatalog {
            get {
                return ResourceManager.GetString("ResolvedUsingCatalog", resourceCulture);
            }
        }
        
        public static string RunNgen {
            get {
                return ResourceManager.GetString("RunNgen", resourceCulture);
            }
        }
        
        public static string SelectedImplementations {
            get {
                return ResourceManager.GetString("SelectedImplementations", resourceCulture);
            }
        }
        
        public static string SelfUpdateAvailable {
            get {
                return ResourceManager.GetString("SelfUpdateAvailable", resourceCulture);
            }
        }
        
        public static string SelfUpdateDisabled {
            get {
                return ResourceManager.GetString("SelfUpdateDisabled", resourceCulture);
            }
        }
        
        public static string SelfUpdateBlocked {
            get {
                return ResourceManager.GetString("SelfUpdateBlocked", resourceCulture);
            }
        }
        
        public static string StabilityPolicyAutoSet {
            get {
                return ResourceManager.GetString("StabilityPolicyAutoSet", resourceCulture);
            }
        }
        
        public static string StabilityPolicyReset {
            get {
                return ResourceManager.GetString("StabilityPolicyReset", resourceCulture);
            }
        }
        
        public static string StabilityPolicySingleImplementation {
            get {
                return ResourceManager.GetString("StabilityPolicySingleImplementation", resourceCulture);
            }
        }
        
        public static string StartService {
            get {
                return ResourceManager.GetString("StartService", resourceCulture);
            }
        }
        
        public static string StopService {
            get {
                return ResourceManager.GetString("StopService", resourceCulture);
            }
        }
        
        public static string StorageReclaimed {
            get {
                return ResourceManager.GetString("StorageReclaimed", resourceCulture);
            }
        }
        
        public static string StoreAudit {
            get {
                return ResourceManager.GetString("StoreAudit", resourceCulture);
            }
        }
        
        public static string SuccessfullyRemoved {
            get {
                return ResourceManager.GetString("SuccessfullyRemoved", resourceCulture);
            }
        }
        
        public static string SuggestLongPath {
            get {
                return ResourceManager.GetString("SuggestLongPath", resourceCulture);
            }
        }
        
        public static string SupportedValues {
            get {
                return ResourceManager.GetString("SupportedValues", resourceCulture);
            }
        }
        
        public static string SyncCryptoKeyDescription {
            get {
                return ResourceManager.GetString("SyncCryptoKeyDescription", resourceCulture);
            }
        }
        
        public static string TooManyArguments {
            get {
                return ResourceManager.GetString("TooManyArguments", resourceCulture);
            }
        }
        
        public static string TryHelp {
            get {
                return ResourceManager.GetString("TryHelp", resourceCulture);
            }
        }
        
        public static string TryHelpWith {
            get {
                return ResourceManager.GetString("TryHelpWith", resourceCulture);
            }
        }
        
        public static string UnableToLoadCatalog {
            get {
                return ResourceManager.GetString("UnableToLoadCatalog", resourceCulture);
            }
        }
        
        public static string UnableToLoadFeed {
            get {
                return ResourceManager.GetString("UnableToLoadFeed", resourceCulture);
            }
        }
        
        public static string UninstallService {
            get {
                return ResourceManager.GetString("UninstallService", resourceCulture);
            }
        }
        
        public static string UnknownCommand {
            get {
                return ResourceManager.GetString("UnknownCommand", resourceCulture);
            }
        }
        
        public static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
        
        public static string UseDefaultSetting {
            get {
                return ResourceManager.GetString("UseDefaultSetting", resourceCulture);
            }
        }
        
        public static string UseInstead {
            get {
                return ResourceManager.GetString("UseInstead", resourceCulture);
            }
        }
        
        public static string UseSystemLanguage {
            get {
                return ResourceManager.GetString("UseSystemLanguage", resourceCulture);
            }
        }
        
        public static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        public static string VerifyImplementation {
            get {
                return ResourceManager.GetString("VerifyImplementation", resourceCulture);
            }
        }
        
        public static string VersionInformation {
            get {
                return ResourceManager.GetString("VersionInformation", resourceCulture);
            }
        }
        
        public static string Working {
            get {
                return ResourceManager.GetString("Working", resourceCulture);
            }
        }
    }
}
