var annotated_dup =
[
    [ "ZeroInstall", null, [
      [ "Commands", "namespace_zero_install_1_1_commands.html", [
        [ "Basic", "namespace_zero_install_1_1_commands_1_1_basic.html", [
          [ "Exporters", "namespace_zero_install_1_1_commands_1_1_basic_1_1_exporters.html", [
            [ "Exporter", "class_zero_install_1_1_commands_1_1_basic_1_1_exporters_1_1_exporter.html", "class_zero_install_1_1_commands_1_1_basic_1_1_exporters_1_1_exporter" ],
            [ "HelpExporterBase", "class_zero_install_1_1_commands_1_1_basic_1_1_exporters_1_1_help_exporter_base.html", "class_zero_install_1_1_commands_1_1_basic_1_1_exporters_1_1_help_exporter_base" ],
            [ "HtmlHelpExporter", "class_zero_install_1_1_commands_1_1_basic_1_1_exporters_1_1_html_help_exporter.html", "class_zero_install_1_1_commands_1_1_basic_1_1_exporters_1_1_html_help_exporter" ]
          ] ],
          [ "AddFeed", "class_zero_install_1_1_commands_1_1_basic_1_1_add_feed.html", "class_zero_install_1_1_commands_1_1_basic_1_1_add_feed" ],
          [ "AddRemoveFeedCommand", "class_zero_install_1_1_commands_1_1_basic_1_1_add_remove_feed_command.html", "class_zero_install_1_1_commands_1_1_basic_1_1_add_remove_feed_command" ],
          [ "CatalogMan", "class_zero_install_1_1_commands_1_1_basic_1_1_catalog_man.html", "class_zero_install_1_1_commands_1_1_basic_1_1_catalog_man" ],
          [ "Configure", "class_zero_install_1_1_commands_1_1_basic_1_1_configure.html", "class_zero_install_1_1_commands_1_1_basic_1_1_configure" ],
          [ "DefaultCommand", "class_zero_install_1_1_commands_1_1_basic_1_1_default_command.html", "class_zero_install_1_1_commands_1_1_basic_1_1_default_command" ],
          [ "Digest", "class_zero_install_1_1_commands_1_1_basic_1_1_digest.html", "class_zero_install_1_1_commands_1_1_basic_1_1_digest" ],
          [ "Download", "class_zero_install_1_1_commands_1_1_basic_1_1_download.html", "class_zero_install_1_1_commands_1_1_basic_1_1_download" ],
          [ "Export", "class_zero_install_1_1_commands_1_1_basic_1_1_export.html", "class_zero_install_1_1_commands_1_1_basic_1_1_export" ],
          [ "ExportHelp", "class_zero_install_1_1_commands_1_1_basic_1_1_export_help.html", "class_zero_install_1_1_commands_1_1_basic_1_1_export_help" ],
          [ "Fetch", "class_zero_install_1_1_commands_1_1_basic_1_1_fetch.html", "class_zero_install_1_1_commands_1_1_basic_1_1_fetch" ],
          [ "Import", "class_zero_install_1_1_commands_1_1_basic_1_1_import.html", "class_zero_install_1_1_commands_1_1_basic_1_1_import" ],
          [ "List", "class_zero_install_1_1_commands_1_1_basic_1_1_list.html", "class_zero_install_1_1_commands_1_1_basic_1_1_list" ],
          [ "ListFeeds", "class_zero_install_1_1_commands_1_1_basic_1_1_list_feeds.html", "class_zero_install_1_1_commands_1_1_basic_1_1_list_feeds" ],
          [ "RemoveFeed", "class_zero_install_1_1_commands_1_1_basic_1_1_remove_feed.html", "class_zero_install_1_1_commands_1_1_basic_1_1_remove_feed" ],
          [ "Run", "class_zero_install_1_1_commands_1_1_basic_1_1_run.html", "class_zero_install_1_1_commands_1_1_basic_1_1_run" ],
          [ "Search", "class_zero_install_1_1_commands_1_1_basic_1_1_search.html", "class_zero_install_1_1_commands_1_1_basic_1_1_search" ],
          [ "Selection", "class_zero_install_1_1_commands_1_1_basic_1_1_selection.html", "class_zero_install_1_1_commands_1_1_basic_1_1_selection" ],
          [ "StoreMan", "class_zero_install_1_1_commands_1_1_basic_1_1_store_man.html", "class_zero_install_1_1_commands_1_1_basic_1_1_store_man" ],
          [ "Update", "class_zero_install_1_1_commands_1_1_basic_1_1_update.html", "class_zero_install_1_1_commands_1_1_basic_1_1_update" ]
        ] ],
        [ "Desktop", "namespace_zero_install_1_1_commands_1_1_desktop.html", [
          [ "SelfManagement", "namespace_zero_install_1_1_commands_1_1_desktop_1_1_self_management.html", [
            [ "SelfManager", "class_zero_install_1_1_commands_1_1_desktop_1_1_self_management_1_1_self_manager.html", "class_zero_install_1_1_commands_1_1_desktop_1_1_self_management_1_1_self_manager" ]
          ] ],
          [ "AddAlias", "class_zero_install_1_1_commands_1_1_desktop_1_1_add_alias.html", "class_zero_install_1_1_commands_1_1_desktop_1_1_add_alias" ],
          [ "AddApp", "class_zero_install_1_1_commands_1_1_desktop_1_1_add_app.html", "class_zero_install_1_1_commands_1_1_desktop_1_1_add_app" ],
          [ "AppCommand", "class_zero_install_1_1_commands_1_1_desktop_1_1_app_command.html", "class_zero_install_1_1_commands_1_1_desktop_1_1_app_command" ],
          [ "Central", "class_zero_install_1_1_commands_1_1_desktop_1_1_central.html", "class_zero_install_1_1_commands_1_1_desktop_1_1_central" ],
          [ "ImportApps", "class_zero_install_1_1_commands_1_1_desktop_1_1_import_apps.html", "class_zero_install_1_1_commands_1_1_desktop_1_1_import_apps" ],
          [ "IntegrateApp", "class_zero_install_1_1_commands_1_1_desktop_1_1_integrate_app.html", "class_zero_install_1_1_commands_1_1_desktop_1_1_integrate_app" ],
          [ "IntegrationCommand", "class_zero_install_1_1_commands_1_1_desktop_1_1_integration_command.html", "class_zero_install_1_1_commands_1_1_desktop_1_1_integration_command" ],
          [ "ListApps", "class_zero_install_1_1_commands_1_1_desktop_1_1_list_apps.html", "class_zero_install_1_1_commands_1_1_desktop_1_1_list_apps" ],
          [ "RemoveAllApps", "class_zero_install_1_1_commands_1_1_desktop_1_1_remove_all_apps.html", "class_zero_install_1_1_commands_1_1_desktop_1_1_remove_all_apps" ],
          [ "RemoveApp", "class_zero_install_1_1_commands_1_1_desktop_1_1_remove_app.html", "class_zero_install_1_1_commands_1_1_desktop_1_1_remove_app" ],
          [ "RepairApps", "class_zero_install_1_1_commands_1_1_desktop_1_1_repair_apps.html", "class_zero_install_1_1_commands_1_1_desktop_1_1_repair_apps" ],
          [ "Self", "class_zero_install_1_1_commands_1_1_desktop_1_1_self.html", "class_zero_install_1_1_commands_1_1_desktop_1_1_self" ],
          [ "SyncApps", "class_zero_install_1_1_commands_1_1_desktop_1_1_sync_apps.html", "class_zero_install_1_1_commands_1_1_desktop_1_1_sync_apps" ],
          [ "UpdateApps", "class_zero_install_1_1_commands_1_1_desktop_1_1_update_apps.html", "class_zero_install_1_1_commands_1_1_desktop_1_1_update_apps" ]
        ] ],
        [ "CliCommand", "class_zero_install_1_1_commands_1_1_cli_command.html", "class_zero_install_1_1_commands_1_1_cli_command" ],
        [ "CliCommandHandler", "class_zero_install_1_1_commands_1_1_cli_command_handler.html", "class_zero_install_1_1_commands_1_1_cli_command_handler" ],
        [ "CliMultiCommand", "class_zero_install_1_1_commands_1_1_cli_multi_command.html", "class_zero_install_1_1_commands_1_1_cli_multi_command" ],
        [ "ICliSubCommand", "interface_zero_install_1_1_commands_1_1_i_cli_sub_command.html", "interface_zero_install_1_1_commands_1_1_i_cli_sub_command" ],
        [ "ICommandHandler", "interface_zero_install_1_1_commands_1_1_i_command_handler.html", "interface_zero_install_1_1_commands_1_1_i_command_handler" ],
        [ "NeedsGuiException", "class_zero_install_1_1_commands_1_1_needs_gui_exception.html", "class_zero_install_1_1_commands_1_1_needs_gui_exception" ],
        [ "ProgramUtils", "class_zero_install_1_1_commands_1_1_program_utils.html", "class_zero_install_1_1_commands_1_1_program_utils" ],
        [ "ScopedOperation", "class_zero_install_1_1_commands_1_1_scoped_operation.html", "class_zero_install_1_1_commands_1_1_scoped_operation" ],
        [ "UnsuitableInstallBaseException", "class_zero_install_1_1_commands_1_1_unsuitable_install_base_exception.html", "class_zero_install_1_1_commands_1_1_unsuitable_install_base_exception" ],
        [ "ZeroInstallInstance", "class_zero_install_1_1_commands_1_1_zero_install_instance.html", "class_zero_install_1_1_commands_1_1_zero_install_instance" ]
      ] ],
      [ "DesktopIntegration", "namespace_zero_install_1_1_desktop_integration.html", [
        [ "AccessPoints", "namespace_zero_install_1_1_desktop_integration_1_1_access_points.html", [
          [ "AccessPoint", "class_zero_install_1_1_desktop_integration_1_1_access_points_1_1_access_point.html", "class_zero_install_1_1_desktop_integration_1_1_access_points_1_1_access_point" ],
          [ "AccessPointList", "class_zero_install_1_1_desktop_integration_1_1_access_points_1_1_access_point_list.html", "class_zero_install_1_1_desktop_integration_1_1_access_points_1_1_access_point_list" ],
          [ "AppAlias", "class_zero_install_1_1_desktop_integration_1_1_access_points_1_1_app_alias.html", "class_zero_install_1_1_desktop_integration_1_1_access_points_1_1_app_alias" ],
          [ "AutoPlay", "class_zero_install_1_1_desktop_integration_1_1_access_points_1_1_auto_play.html", "class_zero_install_1_1_desktop_integration_1_1_access_points_1_1_auto_play" ],
          [ "AutoStart", "class_zero_install_1_1_desktop_integration_1_1_access_points_1_1_auto_start.html", "class_zero_install_1_1_desktop_integration_1_1_access_points_1_1_auto_start" ],
          [ "CapabilityRegistration", "class_zero_install_1_1_desktop_integration_1_1_access_points_1_1_capability_registration.html", "class_zero_install_1_1_desktop_integration_1_1_access_points_1_1_capability_registration" ],
          [ "CommandAccessPoint", "class_zero_install_1_1_desktop_integration_1_1_access_points_1_1_command_access_point.html", "class_zero_install_1_1_desktop_integration_1_1_access_points_1_1_command_access_point" ],
          [ "ContextMenu", "class_zero_install_1_1_desktop_integration_1_1_access_points_1_1_context_menu.html", "class_zero_install_1_1_desktop_integration_1_1_access_points_1_1_context_menu" ],
          [ "DefaultAccessPoint", "class_zero_install_1_1_desktop_integration_1_1_access_points_1_1_default_access_point.html", "class_zero_install_1_1_desktop_integration_1_1_access_points_1_1_default_access_point" ],
          [ "DefaultProgram", "class_zero_install_1_1_desktop_integration_1_1_access_points_1_1_default_program.html", "class_zero_install_1_1_desktop_integration_1_1_access_points_1_1_default_program" ],
          [ "DesktopIcon", "class_zero_install_1_1_desktop_integration_1_1_access_points_1_1_desktop_icon.html", "class_zero_install_1_1_desktop_integration_1_1_access_points_1_1_desktop_icon" ],
          [ "FileType", "class_zero_install_1_1_desktop_integration_1_1_access_points_1_1_file_type.html", "class_zero_install_1_1_desktop_integration_1_1_access_points_1_1_file_type" ],
          [ "IconAccessPoint", "class_zero_install_1_1_desktop_integration_1_1_access_points_1_1_icon_access_point.html", null ],
          [ "MenuEntry", "class_zero_install_1_1_desktop_integration_1_1_access_points_1_1_menu_entry.html", "class_zero_install_1_1_desktop_integration_1_1_access_points_1_1_menu_entry" ],
          [ "MockAccessPoint", "class_zero_install_1_1_desktop_integration_1_1_access_points_1_1_mock_access_point.html", "class_zero_install_1_1_desktop_integration_1_1_access_points_1_1_mock_access_point" ],
          [ "QuickLaunch", "class_zero_install_1_1_desktop_integration_1_1_access_points_1_1_quick_launch.html", "class_zero_install_1_1_desktop_integration_1_1_access_points_1_1_quick_launch" ],
          [ "SendTo", "class_zero_install_1_1_desktop_integration_1_1_access_points_1_1_send_to.html", "class_zero_install_1_1_desktop_integration_1_1_access_points_1_1_send_to" ],
          [ "UrlProtocol", "class_zero_install_1_1_desktop_integration_1_1_access_points_1_1_url_protocol.html", "class_zero_install_1_1_desktop_integration_1_1_access_points_1_1_url_protocol" ]
        ] ],
        [ "Unix", "namespace_zero_install_1_1_desktop_integration_1_1_unix.html", [
          [ "AppAlias", "class_zero_install_1_1_desktop_integration_1_1_unix_1_1_app_alias.html", "class_zero_install_1_1_desktop_integration_1_1_unix_1_1_app_alias" ],
          [ "ContextMenu", "class_zero_install_1_1_desktop_integration_1_1_unix_1_1_context_menu.html", "class_zero_install_1_1_desktop_integration_1_1_unix_1_1_context_menu" ],
          [ "DefaultProgram", "class_zero_install_1_1_desktop_integration_1_1_unix_1_1_default_program.html", "class_zero_install_1_1_desktop_integration_1_1_unix_1_1_default_program" ],
          [ "FileType", "class_zero_install_1_1_desktop_integration_1_1_unix_1_1_file_type.html", "class_zero_install_1_1_desktop_integration_1_1_unix_1_1_file_type" ],
          [ "FreeDesktop", "class_zero_install_1_1_desktop_integration_1_1_unix_1_1_free_desktop.html", "class_zero_install_1_1_desktop_integration_1_1_unix_1_1_free_desktop" ],
          [ "UrlProtocol", "class_zero_install_1_1_desktop_integration_1_1_unix_1_1_url_protocol.html", "class_zero_install_1_1_desktop_integration_1_1_unix_1_1_url_protocol" ]
        ] ],
        [ "ViewModel", "namespace_zero_install_1_1_desktop_integration_1_1_view_model.html", [
          [ "AutoPlayModel", "class_zero_install_1_1_desktop_integration_1_1_view_model_1_1_auto_play_model.html", "class_zero_install_1_1_desktop_integration_1_1_view_model_1_1_auto_play_model" ],
          [ "CapabilityModel", "class_zero_install_1_1_desktop_integration_1_1_view_model_1_1_capability_model.html", "class_zero_install_1_1_desktop_integration_1_1_view_model_1_1_capability_model" ],
          [ "CapabilityModelExtensions", "class_zero_install_1_1_desktop_integration_1_1_view_model_1_1_capability_model_extensions.html", "class_zero_install_1_1_desktop_integration_1_1_view_model_1_1_capability_model_extensions" ],
          [ "ContextMenuModel", "class_zero_install_1_1_desktop_integration_1_1_view_model_1_1_context_menu_model.html", "class_zero_install_1_1_desktop_integration_1_1_view_model_1_1_context_menu_model" ],
          [ "DefaultProgramModel", "class_zero_install_1_1_desktop_integration_1_1_view_model_1_1_default_program_model.html", "class_zero_install_1_1_desktop_integration_1_1_view_model_1_1_default_program_model" ],
          [ "FileTypeModel", "class_zero_install_1_1_desktop_integration_1_1_view_model_1_1_file_type_model.html", "class_zero_install_1_1_desktop_integration_1_1_view_model_1_1_file_type_model" ],
          [ "IconCapabilityModel", "class_zero_install_1_1_desktop_integration_1_1_view_model_1_1_icon_capability_model.html", "class_zero_install_1_1_desktop_integration_1_1_view_model_1_1_icon_capability_model" ],
          [ "IntegrationState", "class_zero_install_1_1_desktop_integration_1_1_view_model_1_1_integration_state.html", "class_zero_install_1_1_desktop_integration_1_1_view_model_1_1_integration_state" ],
          [ "UrlProtocolModel", "class_zero_install_1_1_desktop_integration_1_1_view_model_1_1_url_protocol_model.html", "class_zero_install_1_1_desktop_integration_1_1_view_model_1_1_url_protocol_model" ]
        ] ],
        [ "Windows", "namespace_zero_install_1_1_desktop_integration_1_1_windows.html", [
          [ "AppAlias", "class_zero_install_1_1_desktop_integration_1_1_windows_1_1_app_alias.html", "class_zero_install_1_1_desktop_integration_1_1_windows_1_1_app_alias" ],
          [ "AppRegistration", "class_zero_install_1_1_desktop_integration_1_1_windows_1_1_app_registration.html", "class_zero_install_1_1_desktop_integration_1_1_windows_1_1_app_registration" ],
          [ "AutoPlay", "class_zero_install_1_1_desktop_integration_1_1_windows_1_1_auto_play.html", "class_zero_install_1_1_desktop_integration_1_1_windows_1_1_auto_play" ],
          [ "ComServer", "class_zero_install_1_1_desktop_integration_1_1_windows_1_1_com_server.html", "class_zero_install_1_1_desktop_integration_1_1_windows_1_1_com_server" ],
          [ "ContextMenu", "class_zero_install_1_1_desktop_integration_1_1_windows_1_1_context_menu.html", "class_zero_install_1_1_desktop_integration_1_1_windows_1_1_context_menu" ],
          [ "DefaultProgram", "class_zero_install_1_1_desktop_integration_1_1_windows_1_1_default_program.html", "class_zero_install_1_1_desktop_integration_1_1_windows_1_1_default_program" ],
          [ "FileType", "class_zero_install_1_1_desktop_integration_1_1_windows_1_1_file_type.html", "class_zero_install_1_1_desktop_integration_1_1_windows_1_1_file_type" ],
          [ "PathEnv", "class_zero_install_1_1_desktop_integration_1_1_windows_1_1_path_env.html", "class_zero_install_1_1_desktop_integration_1_1_windows_1_1_path_env" ],
          [ "RegistryClasses", "class_zero_install_1_1_desktop_integration_1_1_windows_1_1_registry_classes.html", "class_zero_install_1_1_desktop_integration_1_1_windows_1_1_registry_classes" ],
          [ "Shortcut", "class_zero_install_1_1_desktop_integration_1_1_windows_1_1_shortcut.html", "class_zero_install_1_1_desktop_integration_1_1_windows_1_1_shortcut" ],
          [ "UrlProtocol", "class_zero_install_1_1_desktop_integration_1_1_windows_1_1_url_protocol.html", "class_zero_install_1_1_desktop_integration_1_1_windows_1_1_url_protocol" ]
        ] ],
        [ "AppEntry", "class_zero_install_1_1_desktop_integration_1_1_app_entry.html", "class_zero_install_1_1_desktop_integration_1_1_app_entry" ],
        [ "AppList", "class_zero_install_1_1_desktop_integration_1_1_app_list.html", "class_zero_install_1_1_desktop_integration_1_1_app_list" ],
        [ "CapabilityExtensions", "class_zero_install_1_1_desktop_integration_1_1_capability_extensions.html", "class_zero_install_1_1_desktop_integration_1_1_capability_extensions" ],
        [ "CategoryIntegrationManager", "class_zero_install_1_1_desktop_integration_1_1_category_integration_manager.html", "class_zero_install_1_1_desktop_integration_1_1_category_integration_manager" ],
        [ "ConflictDataUtils", "class_zero_install_1_1_desktop_integration_1_1_conflict_data_utils.html", "class_zero_install_1_1_desktop_integration_1_1_conflict_data_utils" ],
        [ "ConflictException", "class_zero_install_1_1_desktop_integration_1_1_conflict_exception.html", "class_zero_install_1_1_desktop_integration_1_1_conflict_exception" ],
        [ "ICategoryIntegrationManager", "interface_zero_install_1_1_desktop_integration_1_1_i_category_integration_manager.html", "interface_zero_install_1_1_desktop_integration_1_1_i_category_integration_manager" ],
        [ "IIntegrationManager", "interface_zero_install_1_1_desktop_integration_1_1_i_integration_manager.html", "interface_zero_install_1_1_desktop_integration_1_1_i_integration_manager" ],
        [ "IntegrationManager", "class_zero_install_1_1_desktop_integration_1_1_integration_manager.html", "class_zero_install_1_1_desktop_integration_1_1_integration_manager" ],
        [ "IntegrationManagerBase", "class_zero_install_1_1_desktop_integration_1_1_integration_manager_base.html", "class_zero_install_1_1_desktop_integration_1_1_integration_manager_base" ],
        [ "Suggest", "class_zero_install_1_1_desktop_integration_1_1_suggest.html", "class_zero_install_1_1_desktop_integration_1_1_suggest" ],
        [ "SyncIntegrationManager", "class_zero_install_1_1_desktop_integration_1_1_sync_integration_manager.html", "class_zero_install_1_1_desktop_integration_1_1_sync_integration_manager" ],
        [ "SyncRaceException", "class_zero_install_1_1_desktop_integration_1_1_sync_race_exception.html", "class_zero_install_1_1_desktop_integration_1_1_sync_race_exception" ]
      ] ],
      [ "Model", "namespace_zero_install_1_1_model.html", [
        [ "Capabilities", "namespace_zero_install_1_1_model_1_1_capabilities.html", [
          [ "AppRegistration", "class_zero_install_1_1_model_1_1_capabilities_1_1_app_registration.html", "class_zero_install_1_1_model_1_1_capabilities_1_1_app_registration" ],
          [ "AutoPlay", "class_zero_install_1_1_model_1_1_capabilities_1_1_auto_play.html", "class_zero_install_1_1_model_1_1_capabilities_1_1_auto_play" ],
          [ "AutoPlayEvent", "class_zero_install_1_1_model_1_1_capabilities_1_1_auto_play_event.html", "class_zero_install_1_1_model_1_1_capabilities_1_1_auto_play_event" ],
          [ "Capability", "class_zero_install_1_1_model_1_1_capabilities_1_1_capability.html", "class_zero_install_1_1_model_1_1_capabilities_1_1_capability" ],
          [ "CapabilityList", "class_zero_install_1_1_model_1_1_capabilities_1_1_capability_list.html", "class_zero_install_1_1_model_1_1_capabilities_1_1_capability_list" ],
          [ "CapabilityListExtensions", "class_zero_install_1_1_model_1_1_capabilities_1_1_capability_list_extensions.html", "class_zero_install_1_1_model_1_1_capabilities_1_1_capability_list_extensions" ],
          [ "ComServer", "class_zero_install_1_1_model_1_1_capabilities_1_1_com_server.html", "class_zero_install_1_1_model_1_1_capabilities_1_1_com_server" ],
          [ "ContextMenu", "class_zero_install_1_1_model_1_1_capabilities_1_1_context_menu.html", "class_zero_install_1_1_model_1_1_capabilities_1_1_context_menu" ],
          [ "DefaultCapability", "class_zero_install_1_1_model_1_1_capabilities_1_1_default_capability.html", "class_zero_install_1_1_model_1_1_capabilities_1_1_default_capability" ],
          [ "DefaultProgram", "class_zero_install_1_1_model_1_1_capabilities_1_1_default_program.html", "class_zero_install_1_1_model_1_1_capabilities_1_1_default_program" ],
          [ "FileType", "class_zero_install_1_1_model_1_1_capabilities_1_1_file_type.html", "class_zero_install_1_1_model_1_1_capabilities_1_1_file_type" ],
          [ "FileTypeExtension", "class_zero_install_1_1_model_1_1_capabilities_1_1_file_type_extension.html", "class_zero_install_1_1_model_1_1_capabilities_1_1_file_type_extension" ],
          [ "IconCapability", "class_zero_install_1_1_model_1_1_capabilities_1_1_icon_capability.html", "class_zero_install_1_1_model_1_1_capabilities_1_1_icon_capability" ],
          [ "InstallCommands", "struct_zero_install_1_1_model_1_1_capabilities_1_1_install_commands.html", "struct_zero_install_1_1_model_1_1_capabilities_1_1_install_commands" ],
          [ "KnownProtocolPrefix", "class_zero_install_1_1_model_1_1_capabilities_1_1_known_protocol_prefix.html", "class_zero_install_1_1_model_1_1_capabilities_1_1_known_protocol_prefix" ],
          [ "UrlProtocol", "class_zero_install_1_1_model_1_1_capabilities_1_1_url_protocol.html", "class_zero_install_1_1_model_1_1_capabilities_1_1_url_protocol" ],
          [ "Verb", "class_zero_install_1_1_model_1_1_capabilities_1_1_verb.html", "class_zero_install_1_1_model_1_1_capabilities_1_1_verb" ],
          [ "VerbCapability", "class_zero_install_1_1_model_1_1_capabilities_1_1_verb_capability.html", "class_zero_install_1_1_model_1_1_capabilities_1_1_verb_capability" ]
        ] ],
        [ "Design", "namespace_zero_install_1_1_model_1_1_design.html", [
          [ "ArchitectureConverter", "class_zero_install_1_1_model_1_1_design_1_1_architecture_converter.html", "class_zero_install_1_1_model_1_1_design_1_1_architecture_converter" ],
          [ "ArchiveMimeTypeConverter", "class_zero_install_1_1_model_1_1_design_1_1_archive_mime_type_converter.html", "class_zero_install_1_1_model_1_1_design_1_1_archive_mime_type_converter" ],
          [ "ArgBaseConverter", "class_zero_install_1_1_model_1_1_design_1_1_arg_base_converter.html", "class_zero_install_1_1_model_1_1_design_1_1_arg_base_converter" ],
          [ "CategoryNameConverter", "class_zero_install_1_1_model_1_1_design_1_1_category_name_converter.html", "class_zero_install_1_1_model_1_1_design_1_1_category_name_converter" ],
          [ "CommandNameConverter", "class_zero_install_1_1_model_1_1_design_1_1_command_name_converter.html", "class_zero_install_1_1_model_1_1_design_1_1_command_name_converter" ],
          [ "DistributionNameConverter", "class_zero_install_1_1_model_1_1_design_1_1_distribution_name_converter.html", "class_zero_install_1_1_model_1_1_design_1_1_distribution_name_converter" ],
          [ "IconMimeTypeConverter", "class_zero_install_1_1_model_1_1_design_1_1_icon_mime_type_converter.html", "class_zero_install_1_1_model_1_1_design_1_1_icon_mime_type_converter" ],
          [ "InstallCommandsConverter", "class_zero_install_1_1_model_1_1_design_1_1_install_commands_converter.html", "class_zero_install_1_1_model_1_1_design_1_1_install_commands_converter" ],
          [ "LicenseNameConverter", "class_zero_install_1_1_model_1_1_design_1_1_license_name_converter.html", "class_zero_install_1_1_model_1_1_design_1_1_license_name_converter" ],
          [ "ManifestDigestConverter", "class_zero_install_1_1_model_1_1_design_1_1_manifest_digest_converter.html", "class_zero_install_1_1_model_1_1_design_1_1_manifest_digest_converter" ],
          [ "VerbNameConverter", "class_zero_install_1_1_model_1_1_design_1_1_verb_name_converter.html", "class_zero_install_1_1_model_1_1_design_1_1_verb_name_converter" ]
        ] ],
        [ "Preferences", "namespace_zero_install_1_1_model_1_1_preferences.html", [
          [ "FeedPreferences", "class_zero_install_1_1_model_1_1_preferences_1_1_feed_preferences.html", "class_zero_install_1_1_model_1_1_preferences_1_1_feed_preferences" ],
          [ "ImplementationPreferences", "class_zero_install_1_1_model_1_1_preferences_1_1_implementation_preferences.html", "class_zero_install_1_1_model_1_1_preferences_1_1_implementation_preferences" ],
          [ "InterfacePreferences", "class_zero_install_1_1_model_1_1_preferences_1_1_interface_preferences.html", "class_zero_install_1_1_model_1_1_preferences_1_1_interface_preferences" ]
        ] ],
        [ "Selection", "namespace_zero_install_1_1_model_1_1_selection.html", [
          [ "ImplementationSelection", "class_zero_install_1_1_model_1_1_selection_1_1_implementation_selection.html", "class_zero_install_1_1_model_1_1_selection_1_1_implementation_selection" ],
          [ "SelectionCandidate", "class_zero_install_1_1_model_1_1_selection_1_1_selection_candidate.html", "class_zero_install_1_1_model_1_1_selection_1_1_selection_candidate" ],
          [ "Selections", "class_zero_install_1_1_model_1_1_selection_1_1_selections.html", "class_zero_install_1_1_model_1_1_selection_1_1_selections" ],
          [ "TestCase", "class_zero_install_1_1_model_1_1_selection_1_1_test_case.html", "class_zero_install_1_1_model_1_1_selection_1_1_test_case" ],
          [ "TestCaseSet", "class_zero_install_1_1_model_1_1_selection_1_1_test_case_set.html", "class_zero_install_1_1_model_1_1_selection_1_1_test_case_set" ]
        ] ],
        [ "Architecture", "struct_zero_install_1_1_model_1_1_architecture.html", "struct_zero_install_1_1_model_1_1_architecture" ],
        [ "ArchitectureExtensions", "class_zero_install_1_1_model_1_1_architecture_extensions.html", "class_zero_install_1_1_model_1_1_architecture_extensions" ],
        [ "Archive", "class_zero_install_1_1_model_1_1_archive.html", "class_zero_install_1_1_model_1_1_archive" ],
        [ "Arg", "class_zero_install_1_1_model_1_1_arg.html", "class_zero_install_1_1_model_1_1_arg" ],
        [ "ArgBase", "class_zero_install_1_1_model_1_1_arg_base.html", "class_zero_install_1_1_model_1_1_arg_base" ],
        [ "Binding", "class_zero_install_1_1_model_1_1_binding.html", "class_zero_install_1_1_model_1_1_binding" ],
        [ "Catalog", "class_zero_install_1_1_model_1_1_catalog.html", "class_zero_install_1_1_model_1_1_catalog" ],
        [ "Category", "class_zero_install_1_1_model_1_1_category.html", "class_zero_install_1_1_model_1_1_category" ],
        [ "Command", "class_zero_install_1_1_model_1_1_command.html", "class_zero_install_1_1_model_1_1_command" ],
        [ "Constraint", "class_zero_install_1_1_model_1_1_constraint.html", "class_zero_install_1_1_model_1_1_constraint" ],
        [ "CopyFromStep", "class_zero_install_1_1_model_1_1_copy_from_step.html", "class_zero_install_1_1_model_1_1_copy_from_step" ],
        [ "Dependency", "class_zero_install_1_1_model_1_1_dependency.html", "class_zero_install_1_1_model_1_1_dependency" ],
        [ "DependencyContainerExtensions", "class_zero_install_1_1_model_1_1_dependency_container_extensions.html", "class_zero_install_1_1_model_1_1_dependency_container_extensions" ],
        [ "DownloadRetrievalMethod", "class_zero_install_1_1_model_1_1_download_retrieval_method.html", "class_zero_install_1_1_model_1_1_download_retrieval_method" ],
        [ "Element", "class_zero_install_1_1_model_1_1_element.html", "class_zero_install_1_1_model_1_1_element" ],
        [ "EntryPoint", "class_zero_install_1_1_model_1_1_entry_point.html", "class_zero_install_1_1_model_1_1_entry_point" ],
        [ "EnvironmentBinding", "class_zero_install_1_1_model_1_1_environment_binding.html", "class_zero_install_1_1_model_1_1_environment_binding" ],
        [ "ExecutableInBinding", "class_zero_install_1_1_model_1_1_executable_in_binding.html", "class_zero_install_1_1_model_1_1_executable_in_binding" ],
        [ "ExecutableInPath", "class_zero_install_1_1_model_1_1_executable_in_path.html", "class_zero_install_1_1_model_1_1_executable_in_path" ],
        [ "ExecutableInVar", "class_zero_install_1_1_model_1_1_executable_in_var.html", "class_zero_install_1_1_model_1_1_executable_in_var" ],
        [ "Feed", "class_zero_install_1_1_model_1_1_feed.html", "class_zero_install_1_1_model_1_1_feed" ],
        [ "FeedElement", "class_zero_install_1_1_model_1_1_feed_element.html", "class_zero_install_1_1_model_1_1_feed_element" ],
        [ "FeedReference", "class_zero_install_1_1_model_1_1_feed_reference.html", "class_zero_install_1_1_model_1_1_feed_reference" ],
        [ "FeedTarget", "struct_zero_install_1_1_model_1_1_feed_target.html", "struct_zero_install_1_1_model_1_1_feed_target" ],
        [ "FeedUri", "class_zero_install_1_1_model_1_1_feed_uri.html", "class_zero_install_1_1_model_1_1_feed_uri" ],
        [ "ForEachArgs", "class_zero_install_1_1_model_1_1_for_each_args.html", "class_zero_install_1_1_model_1_1_for_each_args" ],
        [ "GenericBinding", "class_zero_install_1_1_model_1_1_generic_binding.html", "class_zero_install_1_1_model_1_1_generic_binding" ],
        [ "Group", "class_zero_install_1_1_model_1_1_group.html", "class_zero_install_1_1_model_1_1_group" ],
        [ "IArgBaseContainer", "interface_zero_install_1_1_model_1_1_i_arg_base_container.html", "interface_zero_install_1_1_model_1_1_i_arg_base_container" ],
        [ "IBindingContainer", "interface_zero_install_1_1_model_1_1_i_binding_container.html", "interface_zero_install_1_1_model_1_1_i_binding_container" ],
        [ "Icon", "class_zero_install_1_1_model_1_1_icon.html", "class_zero_install_1_1_model_1_1_icon" ],
        [ "IconExtensions", "class_zero_install_1_1_model_1_1_icon_extensions.html", "class_zero_install_1_1_model_1_1_icon_extensions" ],
        [ "IDependencyContainer", "interface_zero_install_1_1_model_1_1_i_dependency_container.html", "interface_zero_install_1_1_model_1_1_i_dependency_container" ],
        [ "IDescriptionContainer", "interface_zero_install_1_1_model_1_1_i_description_container.html", "interface_zero_install_1_1_model_1_1_i_description_container" ],
        [ "IElementContainer", "interface_zero_install_1_1_model_1_1_i_element_container.html", "interface_zero_install_1_1_model_1_1_i_element_container" ],
        [ "IIconContainer", "interface_zero_install_1_1_model_1_1_i_icon_container.html", "interface_zero_install_1_1_model_1_1_i_icon_container" ],
        [ "IInterfaceUri", "interface_zero_install_1_1_model_1_1_i_interface_uri.html", "interface_zero_install_1_1_model_1_1_i_interface_uri" ],
        [ "IInterfaceUriBindingContainer", "interface_zero_install_1_1_model_1_1_i_interface_uri_binding_container.html", null ],
        [ "Implementation", "class_zero_install_1_1_model_1_1_implementation.html", "class_zero_install_1_1_model_1_1_implementation" ],
        [ "ImplementationBase", "class_zero_install_1_1_model_1_1_implementation_base.html", "class_zero_install_1_1_model_1_1_implementation_base" ],
        [ "ImplementationVersion", "class_zero_install_1_1_model_1_1_implementation_version.html", "class_zero_install_1_1_model_1_1_implementation_version" ],
        [ "InterfaceReference", "class_zero_install_1_1_model_1_1_interface_reference.html", "class_zero_install_1_1_model_1_1_interface_reference" ],
        [ "IRecipeStep", "interface_zero_install_1_1_model_1_1_i_recipe_step.html", "interface_zero_install_1_1_model_1_1_i_recipe_step" ],
        [ "ISummaryContainer", "interface_zero_install_1_1_model_1_1_i_summary_container.html", "interface_zero_install_1_1_model_1_1_i_summary_container" ],
        [ "JsonStorage", "class_zero_install_1_1_model_1_1_json_storage.html", "class_zero_install_1_1_model_1_1_json_storage" ],
        [ "ManifestDigest", "struct_zero_install_1_1_model_1_1_manifest_digest.html", "struct_zero_install_1_1_model_1_1_manifest_digest" ],
        [ "ManifestDigestPartialEqualityComparer", "class_zero_install_1_1_model_1_1_manifest_digest_partial_equality_comparer.html", "class_zero_install_1_1_model_1_1_manifest_digest_partial_equality_comparer" ],
        [ "ModelUtils", "class_zero_install_1_1_model_1_1_model_utils.html", "class_zero_install_1_1_model_1_1_model_utils" ],
        [ "OverlayBinding", "class_zero_install_1_1_model_1_1_overlay_binding.html", "class_zero_install_1_1_model_1_1_overlay_binding" ],
        [ "PackageImplementation", "class_zero_install_1_1_model_1_1_package_implementation.html", "class_zero_install_1_1_model_1_1_package_implementation" ],
        [ "Recipe", "class_zero_install_1_1_model_1_1_recipe.html", "class_zero_install_1_1_model_1_1_recipe" ],
        [ "RemoveStep", "class_zero_install_1_1_model_1_1_remove_step.html", "class_zero_install_1_1_model_1_1_remove_step" ],
        [ "RenameStep", "class_zero_install_1_1_model_1_1_rename_step.html", "class_zero_install_1_1_model_1_1_rename_step" ],
        [ "Requirements", "class_zero_install_1_1_model_1_1_requirements.html", "class_zero_install_1_1_model_1_1_requirements" ],
        [ "Restriction", "class_zero_install_1_1_model_1_1_restriction.html", "class_zero_install_1_1_model_1_1_restriction" ],
        [ "RetrievalMethod", "class_zero_install_1_1_model_1_1_retrieval_method.html", "class_zero_install_1_1_model_1_1_retrieval_method" ],
        [ "Runner", "class_zero_install_1_1_model_1_1_runner.html", "class_zero_install_1_1_model_1_1_runner" ],
        [ "SingleFile", "class_zero_install_1_1_model_1_1_single_file.html", "class_zero_install_1_1_model_1_1_single_file" ],
        [ "TargetBase", "class_zero_install_1_1_model_1_1_target_base.html", "class_zero_install_1_1_model_1_1_target_base" ],
        [ "VersionDottedList", "struct_zero_install_1_1_model_1_1_version_dotted_list.html", "struct_zero_install_1_1_model_1_1_version_dotted_list" ],
        [ "VersionPart", "struct_zero_install_1_1_model_1_1_version_part.html", "struct_zero_install_1_1_model_1_1_version_part" ],
        [ "VersionRange", "class_zero_install_1_1_model_1_1_version_range.html", "class_zero_install_1_1_model_1_1_version_range" ],
        [ "VersionRangePart", "class_zero_install_1_1_model_1_1_version_range_part.html", "class_zero_install_1_1_model_1_1_version_range_part" ],
        [ "VersionRangePartExact", "class_zero_install_1_1_model_1_1_version_range_part_exact.html", "class_zero_install_1_1_model_1_1_version_range_part_exact" ],
        [ "VersionRangePartExclude", "class_zero_install_1_1_model_1_1_version_range_part_exclude.html", "class_zero_install_1_1_model_1_1_version_range_part_exclude" ],
        [ "VersionRangePartRange", "class_zero_install_1_1_model_1_1_version_range_part_range.html", "class_zero_install_1_1_model_1_1_version_range_part_range" ],
        [ "WorkingDir", "class_zero_install_1_1_model_1_1_working_dir.html", "class_zero_install_1_1_model_1_1_working_dir" ],
        [ "XmlUnknown", "class_zero_install_1_1_model_1_1_xml_unknown.html", "class_zero_install_1_1_model_1_1_xml_unknown" ]
      ] ],
      [ "Publish", "namespace_zero_install_1_1_publish.html", [
        [ "Capture", "namespace_zero_install_1_1_publish_1_1_capture.html", [
          [ "CommandMapper", "class_zero_install_1_1_publish_1_1_capture_1_1_command_mapper.html", "class_zero_install_1_1_publish_1_1_capture_1_1_command_mapper" ],
          [ "RegUtils", "class_zero_install_1_1_publish_1_1_capture_1_1_reg_utils.html", "class_zero_install_1_1_publish_1_1_capture_1_1_reg_utils" ],
          [ "Snapshot", "class_zero_install_1_1_publish_1_1_capture_1_1_snapshot.html", "class_zero_install_1_1_publish_1_1_capture_1_1_snapshot" ],
          [ "SnapshotDiff", "class_zero_install_1_1_publish_1_1_capture_1_1_snapshot_diff.html", "class_zero_install_1_1_publish_1_1_capture_1_1_snapshot_diff" ]
        ] ],
        [ "EntryPoints", "namespace_zero_install_1_1_publish_1_1_entry_points.html", [
          [ "Design", "namespace_zero_install_1_1_publish_1_1_entry_points_1_1_design.html", [
            [ "DotNetVersionConverter", "class_zero_install_1_1_publish_1_1_entry_points_1_1_design_1_1_dot_net_version_converter.html", "class_zero_install_1_1_publish_1_1_entry_points_1_1_design_1_1_dot_net_version_converter" ],
            [ "JavaVersionConverter", "class_zero_install_1_1_publish_1_1_entry_points_1_1_design_1_1_java_version_converter.html", "class_zero_install_1_1_publish_1_1_entry_points_1_1_design_1_1_java_version_converter" ]
          ] ],
          [ "BashScript", "class_zero_install_1_1_publish_1_1_entry_points_1_1_bash_script.html", "class_zero_install_1_1_publish_1_1_entry_points_1_1_bash_script" ],
          [ "Candidate", "class_zero_install_1_1_publish_1_1_entry_points_1_1_candidate.html", "class_zero_install_1_1_publish_1_1_entry_points_1_1_candidate" ],
          [ "Detection", "class_zero_install_1_1_publish_1_1_entry_points_1_1_detection.html", "class_zero_install_1_1_publish_1_1_entry_points_1_1_detection" ],
          [ "DotNetCoreApp", "class_zero_install_1_1_publish_1_1_entry_points_1_1_dot_net_core_app.html", "class_zero_install_1_1_publish_1_1_entry_points_1_1_dot_net_core_app" ],
          [ "DotNetExe", "class_zero_install_1_1_publish_1_1_entry_points_1_1_dot_net_exe.html", "class_zero_install_1_1_publish_1_1_entry_points_1_1_dot_net_exe" ],
          [ "IIconContainer", "interface_zero_install_1_1_publish_1_1_entry_points_1_1_i_icon_container.html", "interface_zero_install_1_1_publish_1_1_entry_points_1_1_i_icon_container" ],
          [ "InterpretedScript", "class_zero_install_1_1_publish_1_1_entry_points_1_1_interpreted_script.html", "class_zero_install_1_1_publish_1_1_entry_points_1_1_interpreted_script" ],
          [ "Java", "class_zero_install_1_1_publish_1_1_entry_points_1_1_java.html", "class_zero_install_1_1_publish_1_1_entry_points_1_1_java" ],
          [ "JavaClass", "class_zero_install_1_1_publish_1_1_entry_points_1_1_java_class.html", "class_zero_install_1_1_publish_1_1_entry_points_1_1_java_class" ],
          [ "JavaJar", "class_zero_install_1_1_publish_1_1_entry_points_1_1_java_jar.html", "class_zero_install_1_1_publish_1_1_entry_points_1_1_java_jar" ],
          [ "MacOSApp", "class_zero_install_1_1_publish_1_1_entry_points_1_1_mac_o_s_app.html", "class_zero_install_1_1_publish_1_1_entry_points_1_1_mac_o_s_app" ],
          [ "NativeExecutable", "class_zero_install_1_1_publish_1_1_entry_points_1_1_native_executable.html", "class_zero_install_1_1_publish_1_1_entry_points_1_1_native_executable" ],
          [ "PEHeader", "class_zero_install_1_1_publish_1_1_entry_points_1_1_p_e_header.html", "class_zero_install_1_1_publish_1_1_entry_points_1_1_p_e_header" ],
          [ "PerlScript", "class_zero_install_1_1_publish_1_1_entry_points_1_1_perl_script.html", "class_zero_install_1_1_publish_1_1_entry_points_1_1_perl_script" ],
          [ "PhpScript", "class_zero_install_1_1_publish_1_1_entry_points_1_1_php_script.html", "class_zero_install_1_1_publish_1_1_entry_points_1_1_php_script" ],
          [ "PosixBinary", "class_zero_install_1_1_publish_1_1_entry_points_1_1_posix_binary.html", "class_zero_install_1_1_publish_1_1_entry_points_1_1_posix_binary" ],
          [ "PosixExecutable", "class_zero_install_1_1_publish_1_1_entry_points_1_1_posix_executable.html", "class_zero_install_1_1_publish_1_1_entry_points_1_1_posix_executable" ],
          [ "PosixScript", "class_zero_install_1_1_publish_1_1_entry_points_1_1_posix_script.html", "class_zero_install_1_1_publish_1_1_entry_points_1_1_posix_script" ],
          [ "PowerShellScript", "class_zero_install_1_1_publish_1_1_entry_points_1_1_power_shell_script.html", "class_zero_install_1_1_publish_1_1_entry_points_1_1_power_shell_script" ],
          [ "PythonScript", "class_zero_install_1_1_publish_1_1_entry_points_1_1_python_script.html", "class_zero_install_1_1_publish_1_1_entry_points_1_1_python_script" ],
          [ "RubyScript", "class_zero_install_1_1_publish_1_1_entry_points_1_1_ruby_script.html", "class_zero_install_1_1_publish_1_1_entry_points_1_1_ruby_script" ],
          [ "WindowsBatch", "class_zero_install_1_1_publish_1_1_entry_points_1_1_windows_batch.html", "class_zero_install_1_1_publish_1_1_entry_points_1_1_windows_batch" ],
          [ "WindowsExe", "class_zero_install_1_1_publish_1_1_entry_points_1_1_windows_exe.html", "class_zero_install_1_1_publish_1_1_entry_points_1_1_windows_exe" ]
        ] ],
        [ "ExternalFetch", "class_zero_install_1_1_publish_1_1_external_fetch.html", "class_zero_install_1_1_publish_1_1_external_fetch" ],
        [ "FeedBuilder", "class_zero_install_1_1_publish_1_1_feed_builder.html", "class_zero_install_1_1_publish_1_1_feed_builder" ],
        [ "FeedEditing", "class_zero_install_1_1_publish_1_1_feed_editing.html", "class_zero_install_1_1_publish_1_1_feed_editing" ],
        [ "FeedUtils", "class_zero_install_1_1_publish_1_1_feed_utils.html", "class_zero_install_1_1_publish_1_1_feed_utils" ],
        [ "ImplementationUtils", "class_zero_install_1_1_publish_1_1_implementation_utils.html", "class_zero_install_1_1_publish_1_1_implementation_utils" ],
        [ "ManifestUtils", "class_zero_install_1_1_publish_1_1_manifest_utils.html", "class_zero_install_1_1_publish_1_1_manifest_utils" ],
        [ "RetrievalMethodUtils", "class_zero_install_1_1_publish_1_1_retrieval_method_utils.html", "class_zero_install_1_1_publish_1_1_retrieval_method_utils" ],
        [ "SignedCatalog", "class_zero_install_1_1_publish_1_1_signed_catalog.html", "class_zero_install_1_1_publish_1_1_signed_catalog" ],
        [ "SignedFeed", "class_zero_install_1_1_publish_1_1_signed_feed.html", "class_zero_install_1_1_publish_1_1_signed_feed" ]
      ] ],
      [ "Services", "namespace_zero_install_1_1_services.html", [
        [ "Executors", "namespace_zero_install_1_1_services_1_1_executors.html", [
          [ "Executor", "class_zero_install_1_1_services_1_1_executors_1_1_executor.html", "class_zero_install_1_1_services_1_1_executors_1_1_executor" ],
          [ "ExecutorException", "class_zero_install_1_1_services_1_1_executors_1_1_executor_exception.html", "class_zero_install_1_1_services_1_1_executors_1_1_executor_exception" ],
          [ "IEnvironmentBuilder", "interface_zero_install_1_1_services_1_1_executors_1_1_i_environment_builder.html", "interface_zero_install_1_1_services_1_1_executors_1_1_i_environment_builder" ],
          [ "IExecutor", "interface_zero_install_1_1_services_1_1_executors_1_1_i_executor.html", "interface_zero_install_1_1_services_1_1_executors_1_1_i_executor" ]
        ] ],
        [ "Feeds", "namespace_zero_install_1_1_services_1_1_feeds.html", [
          [ "CatalogManager", "class_zero_install_1_1_services_1_1_feeds_1_1_catalog_manager.html", "class_zero_install_1_1_services_1_1_feeds_1_1_catalog_manager" ],
          [ "FeedManager", "class_zero_install_1_1_services_1_1_feeds_1_1_feed_manager.html", "class_zero_install_1_1_services_1_1_feeds_1_1_feed_manager" ],
          [ "ReplayAttackException", "class_zero_install_1_1_services_1_1_feeds_1_1_replay_attack_exception.html", "class_zero_install_1_1_services_1_1_feeds_1_1_replay_attack_exception" ],
          [ "TrustManager", "class_zero_install_1_1_services_1_1_feeds_1_1_trust_manager.html", "class_zero_install_1_1_services_1_1_feeds_1_1_trust_manager" ],
          [ "CatalogManagerExtensions", "class_zero_install_1_1_services_1_1_feeds_1_1_catalog_manager_extensions.html", "class_zero_install_1_1_services_1_1_feeds_1_1_catalog_manager_extensions" ],
          [ "FeedManagerExtensions", "class_zero_install_1_1_services_1_1_feeds_1_1_feed_manager_extensions.html", "class_zero_install_1_1_services_1_1_feeds_1_1_feed_manager_extensions" ],
          [ "ICatalogManager", "interface_zero_install_1_1_services_1_1_feeds_1_1_i_catalog_manager.html", "interface_zero_install_1_1_services_1_1_feeds_1_1_i_catalog_manager" ],
          [ "IFeedManager", "interface_zero_install_1_1_services_1_1_feeds_1_1_i_feed_manager.html", "interface_zero_install_1_1_services_1_1_feeds_1_1_i_feed_manager" ],
          [ "ITrustManager", "interface_zero_install_1_1_services_1_1_feeds_1_1_i_trust_manager.html", "interface_zero_install_1_1_services_1_1_feeds_1_1_i_trust_manager" ]
        ] ],
        [ "Fetchers", "namespace_zero_install_1_1_services_1_1_fetchers.html", [
          [ "Fetcher", "class_zero_install_1_1_services_1_1_fetchers_1_1_fetcher.html", "class_zero_install_1_1_services_1_1_fetchers_1_1_fetcher" ],
          [ "FetcherBase", "class_zero_install_1_1_services_1_1_fetchers_1_1_fetcher_base.html", "class_zero_install_1_1_services_1_1_fetchers_1_1_fetcher_base" ],
          [ "IFetcher", "interface_zero_install_1_1_services_1_1_fetchers_1_1_i_fetcher.html", "interface_zero_install_1_1_services_1_1_fetchers_1_1_i_fetcher" ],
          [ "RetrievalMethodRanker", "class_zero_install_1_1_services_1_1_fetchers_1_1_retrieval_method_ranker.html", "class_zero_install_1_1_services_1_1_fetchers_1_1_retrieval_method_ranker" ]
        ] ],
        [ "Native", "namespace_zero_install_1_1_services_1_1_native.html", [
          [ "PackageManagerBase", "class_zero_install_1_1_services_1_1_native_1_1_package_manager_base.html", "class_zero_install_1_1_services_1_1_native_1_1_package_manager_base" ],
          [ "PackageManagers", "class_zero_install_1_1_services_1_1_native_1_1_package_managers.html", "class_zero_install_1_1_services_1_1_native_1_1_package_managers" ],
          [ "StubPackageManager", "class_zero_install_1_1_services_1_1_native_1_1_stub_package_manager.html", "class_zero_install_1_1_services_1_1_native_1_1_stub_package_manager" ],
          [ "WindowsPackageManager", "class_zero_install_1_1_services_1_1_native_1_1_windows_package_manager.html", "class_zero_install_1_1_services_1_1_native_1_1_windows_package_manager" ],
          [ "ExternalImplementation", "class_zero_install_1_1_services_1_1_native_1_1_external_implementation.html", "class_zero_install_1_1_services_1_1_native_1_1_external_implementation" ],
          [ "ExternalRetrievalMethod", "class_zero_install_1_1_services_1_1_native_1_1_external_retrieval_method.html", "class_zero_install_1_1_services_1_1_native_1_1_external_retrieval_method" ],
          [ "IPackageManager", "interface_zero_install_1_1_services_1_1_native_1_1_i_package_manager.html", "interface_zero_install_1_1_services_1_1_native_1_1_i_package_manager" ]
        ] ],
        [ "Solvers", "namespace_zero_install_1_1_services_1_1_solvers.html", [
          [ "BacktrackingSolver", "class_zero_install_1_1_services_1_1_solvers_1_1_backtracking_solver.html", "class_zero_install_1_1_services_1_1_solvers_1_1_backtracking_solver" ],
          [ "ExternalSolver", "class_zero_install_1_1_services_1_1_solvers_1_1_external_solver.html", "class_zero_install_1_1_services_1_1_solvers_1_1_external_solver" ],
          [ "ExternalSolverSession", "class_zero_install_1_1_services_1_1_solvers_1_1_external_solver_session.html", "class_zero_install_1_1_services_1_1_solvers_1_1_external_solver_session" ],
          [ "FallbackSolver", "class_zero_install_1_1_services_1_1_solvers_1_1_fallback_solver.html", "class_zero_install_1_1_services_1_1_solvers_1_1_fallback_solver" ],
          [ "SelectionCandidateProvider", "class_zero_install_1_1_services_1_1_solvers_1_1_selection_candidate_provider.html", "class_zero_install_1_1_services_1_1_solvers_1_1_selection_candidate_provider" ],
          [ "SolverRunBase", "class_zero_install_1_1_services_1_1_solvers_1_1_solver_run_base.html", "class_zero_install_1_1_services_1_1_solvers_1_1_solver_run_base" ],
          [ "ISelectionCandidateProvider", "interface_zero_install_1_1_services_1_1_solvers_1_1_i_selection_candidate_provider.html", "interface_zero_install_1_1_services_1_1_solvers_1_1_i_selection_candidate_provider" ],
          [ "ISolver", "interface_zero_install_1_1_services_1_1_solvers_1_1_i_solver.html", "interface_zero_install_1_1_services_1_1_solvers_1_1_i_solver" ],
          [ "SolverException", "class_zero_install_1_1_services_1_1_solvers_1_1_solver_exception.html", "class_zero_install_1_1_services_1_1_solvers_1_1_solver_exception" ],
          [ "SolverExtensions", "class_zero_install_1_1_services_1_1_solvers_1_1_solver_extensions.html", "class_zero_install_1_1_services_1_1_solvers_1_1_solver_extensions" ],
          [ "SolverUtils", "class_zero_install_1_1_services_1_1_solvers_1_1_solver_utils.html", "class_zero_install_1_1_services_1_1_solvers_1_1_solver_utils" ]
        ] ],
        [ "SelectionsManager", "class_zero_install_1_1_services_1_1_selections_manager.html", "class_zero_install_1_1_services_1_1_selections_manager" ],
        [ "ServiceLocator", "class_zero_install_1_1_services_1_1_service_locator.html", "class_zero_install_1_1_services_1_1_service_locator" ],
        [ "ISelectionsManager", "interface_zero_install_1_1_services_1_1_i_selections_manager.html", "interface_zero_install_1_1_services_1_1_i_selections_manager" ],
        [ "SelectionsManagerExtensions", "class_zero_install_1_1_services_1_1_selections_manager_extensions.html", "class_zero_install_1_1_services_1_1_selections_manager_extensions" ]
      ] ],
      [ "Store", "namespace_zero_install_1_1_store.html", [
        [ "Feeds", "namespace_zero_install_1_1_store_1_1_feeds.html", [
          [ "FeedCache", "class_zero_install_1_1_store_1_1_feeds_1_1_feed_cache.html", "class_zero_install_1_1_store_1_1_feeds_1_1_feed_cache" ],
          [ "FeedCacheExtensions", "class_zero_install_1_1_store_1_1_feeds_1_1_feed_cache_extensions.html", "class_zero_install_1_1_store_1_1_feeds_1_1_feed_cache_extensions" ],
          [ "FeedCaches", "class_zero_install_1_1_store_1_1_feeds_1_1_feed_caches.html", "class_zero_install_1_1_store_1_1_feeds_1_1_feed_caches" ],
          [ "FeedExtensions", "class_zero_install_1_1_store_1_1_feeds_1_1_feed_extensions.html", "class_zero_install_1_1_store_1_1_feeds_1_1_feed_extensions" ],
          [ "FeedUtils", "class_zero_install_1_1_store_1_1_feeds_1_1_feed_utils.html", "class_zero_install_1_1_store_1_1_feeds_1_1_feed_utils" ],
          [ "IFeedCache", "interface_zero_install_1_1_store_1_1_feeds_1_1_i_feed_cache.html", "interface_zero_install_1_1_store_1_1_feeds_1_1_i_feed_cache" ],
          [ "SearchResult", "class_zero_install_1_1_store_1_1_feeds_1_1_search_result.html", "class_zero_install_1_1_store_1_1_feeds_1_1_search_result" ],
          [ "SearchResults", "class_zero_install_1_1_store_1_1_feeds_1_1_search_results.html", "class_zero_install_1_1_store_1_1_feeds_1_1_search_results" ]
        ] ],
        [ "Implementations", "namespace_zero_install_1_1_store_1_1_implementations.html", [
          [ "Archives", "namespace_zero_install_1_1_store_1_1_implementations_1_1_archives.html", [
            [ "ArchiveExtractor", "class_zero_install_1_1_store_1_1_implementations_1_1_archives_1_1_archive_extractor.html", "class_zero_install_1_1_store_1_1_implementations_1_1_archives_1_1_archive_extractor" ],
            [ "ArchiveGenerator", "class_zero_install_1_1_store_1_1_implementations_1_1_archives_1_1_archive_generator.html", "class_zero_install_1_1_store_1_1_implementations_1_1_archives_1_1_archive_generator" ],
            [ "RarExtractor", "class_zero_install_1_1_store_1_1_implementations_1_1_archives_1_1_rar_extractor.html", "class_zero_install_1_1_store_1_1_implementations_1_1_archives_1_1_rar_extractor" ],
            [ "RubyGemExtractor", "class_zero_install_1_1_store_1_1_implementations_1_1_archives_1_1_ruby_gem_extractor.html", "class_zero_install_1_1_store_1_1_implementations_1_1_archives_1_1_ruby_gem_extractor" ],
            [ "SevenZipExtractor", "class_zero_install_1_1_store_1_1_implementations_1_1_archives_1_1_seven_zip_extractor.html", "class_zero_install_1_1_store_1_1_implementations_1_1_archives_1_1_seven_zip_extractor" ],
            [ "TarBz2Extractor", "class_zero_install_1_1_store_1_1_implementations_1_1_archives_1_1_tar_bz2_extractor.html", "class_zero_install_1_1_store_1_1_implementations_1_1_archives_1_1_tar_bz2_extractor" ],
            [ "TarBz2Generator", "class_zero_install_1_1_store_1_1_implementations_1_1_archives_1_1_tar_bz2_generator.html", "class_zero_install_1_1_store_1_1_implementations_1_1_archives_1_1_tar_bz2_generator" ],
            [ "TarExtractor", "class_zero_install_1_1_store_1_1_implementations_1_1_archives_1_1_tar_extractor.html", "class_zero_install_1_1_store_1_1_implementations_1_1_archives_1_1_tar_extractor" ],
            [ "TarGenerator", "class_zero_install_1_1_store_1_1_implementations_1_1_archives_1_1_tar_generator.html", "class_zero_install_1_1_store_1_1_implementations_1_1_archives_1_1_tar_generator" ],
            [ "TarGzExtractor", "class_zero_install_1_1_store_1_1_implementations_1_1_archives_1_1_tar_gz_extractor.html", "class_zero_install_1_1_store_1_1_implementations_1_1_archives_1_1_tar_gz_extractor" ],
            [ "TarGzGenerator", "class_zero_install_1_1_store_1_1_implementations_1_1_archives_1_1_tar_gz_generator.html", "class_zero_install_1_1_store_1_1_implementations_1_1_archives_1_1_tar_gz_generator" ],
            [ "TarLzipExtractor", "class_zero_install_1_1_store_1_1_implementations_1_1_archives_1_1_tar_lzip_extractor.html", "class_zero_install_1_1_store_1_1_implementations_1_1_archives_1_1_tar_lzip_extractor" ],
            [ "TarLzmaExtractor", "class_zero_install_1_1_store_1_1_implementations_1_1_archives_1_1_tar_lzma_extractor.html", "class_zero_install_1_1_store_1_1_implementations_1_1_archives_1_1_tar_lzma_extractor" ],
            [ "TarXzExtractor", "class_zero_install_1_1_store_1_1_implementations_1_1_archives_1_1_tar_xz_extractor.html", "class_zero_install_1_1_store_1_1_implementations_1_1_archives_1_1_tar_xz_extractor" ],
            [ "TarZstandardExtractor", "class_zero_install_1_1_store_1_1_implementations_1_1_archives_1_1_tar_zstandard_extractor.html", "class_zero_install_1_1_store_1_1_implementations_1_1_archives_1_1_tar_zstandard_extractor" ],
            [ "ZipExtractor", "class_zero_install_1_1_store_1_1_implementations_1_1_archives_1_1_zip_extractor.html", "class_zero_install_1_1_store_1_1_implementations_1_1_archives_1_1_zip_extractor" ],
            [ "ZipGenerator", "class_zero_install_1_1_store_1_1_implementations_1_1_archives_1_1_zip_generator.html", "class_zero_install_1_1_store_1_1_implementations_1_1_archives_1_1_zip_generator" ]
          ] ],
          [ "Build", "namespace_zero_install_1_1_store_1_1_implementations_1_1_build.html", [
            [ "CloneDirectory", "class_zero_install_1_1_store_1_1_implementations_1_1_build_1_1_clone_directory.html", "class_zero_install_1_1_store_1_1_implementations_1_1_build_1_1_clone_directory" ],
            [ "CloneFile", "class_zero_install_1_1_store_1_1_implementations_1_1_build_1_1_clone_file.html", "class_zero_install_1_1_store_1_1_implementations_1_1_build_1_1_clone_file" ],
            [ "DirectoryBuilder", "class_zero_install_1_1_store_1_1_implementations_1_1_build_1_1_directory_builder.html", "class_zero_install_1_1_store_1_1_implementations_1_1_build_1_1_directory_builder" ],
            [ "DirectoryTaskBase", "class_zero_install_1_1_store_1_1_implementations_1_1_build_1_1_directory_task_base.html", "class_zero_install_1_1_store_1_1_implementations_1_1_build_1_1_directory_task_base" ],
            [ "FlagUtils", "class_zero_install_1_1_store_1_1_implementations_1_1_build_1_1_flag_utils.html", "class_zero_install_1_1_store_1_1_implementations_1_1_build_1_1_flag_utils" ],
            [ "RecipeUtils", "class_zero_install_1_1_store_1_1_implementations_1_1_build_1_1_recipe_utils.html", "class_zero_install_1_1_store_1_1_implementations_1_1_build_1_1_recipe_utils" ]
          ] ],
          [ "Deployment", "namespace_zero_install_1_1_store_1_1_implementations_1_1_deployment.html", [
            [ "ClearDirectory", "class_zero_install_1_1_store_1_1_implementations_1_1_deployment_1_1_clear_directory.html", "class_zero_install_1_1_store_1_1_implementations_1_1_deployment_1_1_clear_directory" ],
            [ "DeployDirectory", "class_zero_install_1_1_store_1_1_implementations_1_1_deployment_1_1_deploy_directory.html", "class_zero_install_1_1_store_1_1_implementations_1_1_deployment_1_1_deploy_directory" ],
            [ "DirectoryOperation", "class_zero_install_1_1_store_1_1_implementations_1_1_deployment_1_1_directory_operation.html", "class_zero_install_1_1_store_1_1_implementations_1_1_deployment_1_1_directory_operation" ]
          ] ],
          [ "Manifests", "namespace_zero_install_1_1_store_1_1_implementations_1_1_manifests.html", [
            [ "Manifest", "class_zero_install_1_1_store_1_1_implementations_1_1_manifests_1_1_manifest.html", "class_zero_install_1_1_store_1_1_implementations_1_1_manifests_1_1_manifest" ],
            [ "ManifestFormat", "class_zero_install_1_1_store_1_1_implementations_1_1_manifests_1_1_manifest_format.html", "class_zero_install_1_1_store_1_1_implementations_1_1_manifests_1_1_manifest_format" ],
            [ "ManifestGenerator", "class_zero_install_1_1_store_1_1_implementations_1_1_manifests_1_1_manifest_generator.html", "class_zero_install_1_1_store_1_1_implementations_1_1_manifests_1_1_manifest_generator" ]
          ] ],
          [ "CompositeImplementationStore", "class_zero_install_1_1_store_1_1_implementations_1_1_composite_implementation_store.html", "class_zero_install_1_1_store_1_1_implementations_1_1_composite_implementation_store" ],
          [ "DigestMismatchException", "class_zero_install_1_1_store_1_1_implementations_1_1_digest_mismatch_exception.html", "class_zero_install_1_1_store_1_1_implementations_1_1_digest_mismatch_exception" ],
          [ "FetchHandle", "class_zero_install_1_1_store_1_1_implementations_1_1_fetch_handle.html", "class_zero_install_1_1_store_1_1_implementations_1_1_fetch_handle" ],
          [ "IImplementationStore", "interface_zero_install_1_1_store_1_1_implementations_1_1_i_implementation_store.html", "interface_zero_install_1_1_store_1_1_implementations_1_1_i_implementation_store" ],
          [ "ImplementationAlreadyInStoreException", "class_zero_install_1_1_store_1_1_implementations_1_1_implementation_already_in_store_exception.html", "class_zero_install_1_1_store_1_1_implementations_1_1_implementation_already_in_store_exception" ],
          [ "ImplementationNotFoundException", "class_zero_install_1_1_store_1_1_implementations_1_1_implementation_not_found_exception.html", "class_zero_install_1_1_store_1_1_implementations_1_1_implementation_not_found_exception" ],
          [ "ImplementationStore", "class_zero_install_1_1_store_1_1_implementations_1_1_implementation_store.html", "class_zero_install_1_1_store_1_1_implementations_1_1_implementation_store" ],
          [ "ImplementationStores", "class_zero_install_1_1_store_1_1_implementations_1_1_implementation_stores.html", "class_zero_install_1_1_store_1_1_implementations_1_1_implementation_stores" ],
          [ "ImplementationStoreUtils", "class_zero_install_1_1_store_1_1_implementations_1_1_implementation_store_utils.html", "class_zero_install_1_1_store_1_1_implementations_1_1_implementation_store_utils" ]
        ] ],
        [ "Trust", "namespace_zero_install_1_1_store_1_1_trust.html", [
          [ "BouncyCastle", "class_zero_install_1_1_store_1_1_trust_1_1_bouncy_castle.html", "class_zero_install_1_1_store_1_1_trust_1_1_bouncy_castle" ],
          [ "Domain", "struct_zero_install_1_1_store_1_1_trust_1_1_domain.html", "struct_zero_install_1_1_store_1_1_trust_1_1_domain" ],
          [ "DomainSet", "class_zero_install_1_1_store_1_1_trust_1_1_domain_set.html", "class_zero_install_1_1_store_1_1_trust_1_1_domain_set" ],
          [ "GnuPG", "class_zero_install_1_1_store_1_1_trust_1_1_gnu_p_g.html", "class_zero_install_1_1_store_1_1_trust_1_1_gnu_p_g" ],
          [ "IFingerprintContainer", "interface_zero_install_1_1_store_1_1_trust_1_1_i_fingerprint_container.html", "interface_zero_install_1_1_store_1_1_trust_1_1_i_fingerprint_container" ],
          [ "IKeyIDContainer", "interface_zero_install_1_1_store_1_1_trust_1_1_i_key_i_d_container.html", "interface_zero_install_1_1_store_1_1_trust_1_1_i_key_i_d_container" ],
          [ "IOpenPgp", "interface_zero_install_1_1_store_1_1_trust_1_1_i_open_pgp.html", "interface_zero_install_1_1_store_1_1_trust_1_1_i_open_pgp" ],
          [ "Key", "class_zero_install_1_1_store_1_1_trust_1_1_key.html", "class_zero_install_1_1_store_1_1_trust_1_1_key" ],
          [ "OpenPgp", "class_zero_install_1_1_store_1_1_trust_1_1_open_pgp.html", "class_zero_install_1_1_store_1_1_trust_1_1_open_pgp" ],
          [ "OpenPgpExtensions", "class_zero_install_1_1_store_1_1_trust_1_1_open_pgp_extensions.html", "class_zero_install_1_1_store_1_1_trust_1_1_open_pgp_extensions" ],
          [ "OpenPgpSecretKey", "class_zero_install_1_1_store_1_1_trust_1_1_open_pgp_secret_key.html", "class_zero_install_1_1_store_1_1_trust_1_1_open_pgp_secret_key" ],
          [ "OpenPgpSignature", "class_zero_install_1_1_store_1_1_trust_1_1_open_pgp_signature.html", "class_zero_install_1_1_store_1_1_trust_1_1_open_pgp_signature" ],
          [ "ValidSignature", "class_zero_install_1_1_store_1_1_trust_1_1_valid_signature.html", "class_zero_install_1_1_store_1_1_trust_1_1_valid_signature" ],
          [ "ErrorSignature", "class_zero_install_1_1_store_1_1_trust_1_1_error_signature.html", "class_zero_install_1_1_store_1_1_trust_1_1_error_signature" ],
          [ "BadSignature", "class_zero_install_1_1_store_1_1_trust_1_1_bad_signature.html", "class_zero_install_1_1_store_1_1_trust_1_1_bad_signature" ],
          [ "MissingKeySignature", "class_zero_install_1_1_store_1_1_trust_1_1_missing_key_signature.html", "class_zero_install_1_1_store_1_1_trust_1_1_missing_key_signature" ],
          [ "OpenPgpUtils", "class_zero_install_1_1_store_1_1_trust_1_1_open_pgp_utils.html", "class_zero_install_1_1_store_1_1_trust_1_1_open_pgp_utils" ],
          [ "SignatureException", "class_zero_install_1_1_store_1_1_trust_1_1_signature_exception.html", "class_zero_install_1_1_store_1_1_trust_1_1_signature_exception" ],
          [ "TrustDB", "class_zero_install_1_1_store_1_1_trust_1_1_trust_d_b.html", "class_zero_install_1_1_store_1_1_trust_1_1_trust_d_b" ],
          [ "WrongPassphraseException", "class_zero_install_1_1_store_1_1_trust_1_1_wrong_passphrase_exception.html", "class_zero_install_1_1_store_1_1_trust_1_1_wrong_passphrase_exception" ]
        ] ],
        [ "ViewModel", "namespace_zero_install_1_1_store_1_1_view_model.html", [
          [ "CacheNode", "class_zero_install_1_1_store_1_1_view_model_1_1_cache_node.html", "class_zero_install_1_1_store_1_1_view_model_1_1_cache_node" ],
          [ "CacheNodeBuilder", "class_zero_install_1_1_store_1_1_view_model_1_1_cache_node_builder.html", "class_zero_install_1_1_store_1_1_view_model_1_1_cache_node_builder" ],
          [ "FeedNode", "class_zero_install_1_1_store_1_1_view_model_1_1_feed_node.html", "class_zero_install_1_1_store_1_1_view_model_1_1_feed_node" ],
          [ "ImplementationNode", "class_zero_install_1_1_store_1_1_view_model_1_1_implementation_node.html", "class_zero_install_1_1_store_1_1_view_model_1_1_implementation_node" ],
          [ "OrphanedImplementationNode", "class_zero_install_1_1_store_1_1_view_model_1_1_orphaned_implementation_node.html", "class_zero_install_1_1_store_1_1_view_model_1_1_orphaned_implementation_node" ],
          [ "OwnedImplementationNode", "class_zero_install_1_1_store_1_1_view_model_1_1_owned_implementation_node.html", "class_zero_install_1_1_store_1_1_view_model_1_1_owned_implementation_node" ],
          [ "SelectionsDiffNode", "class_zero_install_1_1_store_1_1_view_model_1_1_selections_diff_node.html", "class_zero_install_1_1_store_1_1_view_model_1_1_selections_diff_node" ],
          [ "StoreNode", "class_zero_install_1_1_store_1_1_view_model_1_1_store_node.html", "class_zero_install_1_1_store_1_1_view_model_1_1_store_node" ],
          [ "TempDirectoryNode", "class_zero_install_1_1_store_1_1_view_model_1_1_temp_directory_node.html", "class_zero_install_1_1_store_1_1_view_model_1_1_temp_directory_node" ],
          [ "TrustNodeExtensions", "class_zero_install_1_1_store_1_1_view_model_1_1_trust_node_extensions.html", "class_zero_install_1_1_store_1_1_view_model_1_1_trust_node_extensions" ]
        ] ],
        [ "Config", "class_zero_install_1_1_store_1_1_config.html", "class_zero_install_1_1_store_1_1_config" ],
        [ "IconStore", "class_zero_install_1_1_store_1_1_icon_store.html", "class_zero_install_1_1_store_1_1_icon_store" ],
        [ "IIconStore", "interface_zero_install_1_1_store_1_1_i_icon_store.html", "interface_zero_install_1_1_store_1_1_i_icon_store" ]
      ] ]
    ] ]
];