image:
- Visual Studio 2017
- Ubuntu

for:
  - matrix:
      only:
        - image: Visual Studio 2017

    before_build:
      - gitversion /l console /output buildserver

    build_script:
      - ps: src\build.ps1 $env:GitVersion_NuGetVersion
      - ps: doc\build.ps1

    test_script:
      - ps: src\test.ps1

    artifacts:
      - path: build\Release\*.nupkg
      - path: build\Documentation
        name: apidocs
      - path: build\Schemas
        name: xml-schemas

    deploy:
      - provider: Environment
        name: GitHub Releases
        on:
          appveyor_repo_tag: true
      - provider: Environment
        name: NuGet
        on:
          appveyor_repo_tag: true

  - matrix:
      only:
        - image: Ubuntu

    build_script:
      - sh: src/build.sh

    test_script:
      - sh: src/test.sh
