image:
  - Visual Studio 2022
  - Ubuntu2004

for:
  - matrix:
      only:
        - image: Visual Studio 2022

    cache:
      - '%USERPROFILE%\.nuget\packages -> **\*.csproj,**\*.targets,**\*.props'

    before_build:
      - powershell .\0install.ps1 run --batch https://apps.0install.net/devel/gitversion.xml /verbosity quiet /output buildserver

    build_script:
      - powershell .\build.ps1 %GitVersion_NuGetVersion% -SkipTest

    test_script:
      - powershell src\test.ps1

    artifacts:
      # nuget.org
      - path: artifacts\Release\*.*nupkg
      # SignPath
      - path: artifacts
      # docs.0install.net
      - path: artifacts\Documentation
        name: docs
      # apps.0install.net
      - path: 0install-dotnet-*.tar.gz
        name: bin
      - path: 0install-dotnet-*.xml
        name: feed

    deploy:
      - provider: Environment
        name: GitHub Releases
        on:
          appveyor_repo_tag: true
      - provider: Environment
        name: NuGet
        on:
          appveyor_repo_tag: true
      - provider: Webhook
        url: https://app.signpath.io/API/v1/0e70cf92-49a1-4427-a800-b6bc5b497936/Integrations/AppVeyor?ProjectSlug=dotnet&SigningPolicySlug=release-signing
        authorization:
           secure: 1lrrvByUN3qR7P/QQN6XXy4LWmh8ls/veOESoeVffvyF4kOqo28JxoZtIxYOZZpAZKlbAv8tWQaLFZiUxXFHmA==
        on:
          appveyor_repo_tag: true

  - matrix:
      only:
        - image: Ubuntu2004

    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: '1'
      DOTNET_NOLOGO: '1'

    cache:
      - '$HOME/.nuget/packages -> **/*.csproj,**/*.targets,**/*.props'

    before_build:
      - ./0install.sh run https://apps.0install.net/devel/gitversion.xml --verbosity quiet --output buildserver

    build_script:
      - ./build.sh $GitVersion_NuGetVersion --skip-test

    test_script:
      - src/test.sh
