image:
  - Visual Studio 2022
  - Ubuntu2004

for:
  - matrix:
      only:
        - image: Visual Studio 2022

    cache:
      - '%USERPROFILE%\.nuget\packages -> **\*.csproj'

    before_build:
      - powershell .\0install.ps1 run --batch https://apps.0install.net/devel/gitversion.xml /l console /output buildserver

    build_script:
      - powershell src\build.ps1 %GitVersion_NuGetVersion%
      - powershell doc\build.ps1

    test_script:
      - powershell src\test.ps1

    artifacts:
      - path: artifacts
      - path: artifacts\Release\*.*nupkg
      - path: artifacts\0install-dotnet-*.tar.gz
        name: bin
      - path: artifacts\Documentation
        name: docs

    deploy:
      - provider: Environment
        name: GitHub Releases
        on:
          appveyor_repo_tag: true
      - provider: Environment
        name: NuGet
        on:
          appveyor_repo_tag: true
      - provider: Webhook
        url: https://app.signpath.io/API/v1/0e70cf92-49a1-4427-a800-b6bc5b497936/Integrations/AppVeyor?ProjectSlug=dotnet&SigningPolicySlug=release-signing
        authorization:
           secure: 1lrrvByUN3qR7P/QQN6XXy4LWmh8ls/veOESoeVffvyF4kOqo28JxoZtIxYOZZpAZKlbAv8tWQaLFZiUxXFHmA==
        on:
          appveyor_repo_tag: true

  - matrix:
      only:
        - image: Ubuntu2004

    cache:
      - '$HOME/.nuget/packages -> **/*.csproj'

    build_script:
      - sh: src/build.sh

    test_script:
      - sh: src/test.sh
