image:
  - Visual Studio 2017
  - Ubuntu1804

for:
  - matrix:
      only:
        - image: Visual Studio 2017

    cache:
      - '%USERPROFILE%\.nuget\packages -> **\*.csproj'
      - '%LOCALAPPDATA%\0install.net'
      - '%APPDATA%\0install.net'

    before_build:
      - gitversion /l console /output buildserver

    build_script:
      - ps: src\build.ps1 $env:GitVersion_NuGetVersion
      - ps: feed\build.ps1 $env:GitVersion_NuGetVersion -GitHubRelease:$($env:APPVEYOR_REPO_TAG -eq "true")

    test_script:
      - ps: src\test.ps1

    artifacts:
      - path: feed\*.xml
      - path: feed\*.tar.gz
      - path: artifacts\Release\*.nupkg
      - path: artifacts\Schemas
        name: schemas

    deploy:
      - provider: Environment
        name: GitHub Releases
        on:
          appveyor_repo_tag: true
      - provider: Environment
        name: NuGet
        on:
          appveyor_repo_tag: true

  - matrix:
      only:
        - image: Ubuntu1804

    cache:
      - '$HOME/.nuget/packages -> **/*.csproj'

    build_script:
      - sh: src/build.sh

    test_script:
      - sh: src/test.sh
