image:
  - Visual Studio 2019
  - Ubuntu1804

for:
  - matrix:
      only:
        - image: Visual Studio 2019

    cache:
      - '%USERPROFILE%\.nuget\packages -> **\*.csproj'

    before_build:
      - choco install GitVersion.Portable --version 4.0.0
      - gitversion /l console /output buildserver

    build_script:
      - ps: src\build.ps1 $env:GitVersion_NuGetVersion

    test_script:
      - ps: src\test.ps1

    artifacts:
      - path: artifacts
      - path: artifacts\0install-dotnet-*.tar.gz
      - path: artifacts\Release\*.*nupkg

    deploy:
      - provider: Webhook
        url: https://app.signpath.io/API/v1/0e70cf92-49a1-4427-a800-b6bc5b497936/Integrations/AppVeyor?ProjectSlug=dotnet&SigningPolicySlug=release-signing
        authorization:
           secure: 1lrrvByUN3qR7P/QQN6XXy4LWmh8ls/veOESoeVffvyF4kOqo28JxoZtIxYOZZpAZKlbAv8tWQaLFZiUxXFHmA==
        on:
          appveyor_repo_tag: true

  - matrix:
      only:
        - image: Ubuntu1804

    cache:
      - '$HOME/.nuget/packages -> **/*.csproj'

    build_script:
      - sh: src/build.sh

    test_script:
      - sh: src/test.sh
