var namespace_zero_install_1_1_publish_1_1_entry_points_1_1_design =
[
    [ "DotNetVersionConverter", "class_zero_install_1_1_publish_1_1_entry_points_1_1_design_1_1_dot_net_version_converter.html", "class_zero_install_1_1_publish_1_1_entry_points_1_1_design_1_1_dot_net_version_converter" ],
    [ "JavaVersionConverter", "class_zero_install_1_1_publish_1_1_entry_points_1_1_design_1_1_java_version_converter.html", "class_zero_install_1_1_publish_1_1_entry_points_1_1_design_1_1_java_version_converter" ]
];