//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroInstall.Publish.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZeroInstall.Publish.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All implementations have already been released. Select a specific version instead..
        /// </summary>
        internal static string AllImplementationsReleased {
            get {
                return ResourceManager.GetString("AllImplementationsReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The archive contains only a single top-level directory '{0}'. You should probably set the '{1}' attribute to '{0}' to avoid an extra nesting level..
        /// </summary>
        internal static string ArchiveContainsSingleTopLevelDirectory {
            get {
                return ResourceManager.GetString("ArchiveContainsSingleTopLevelDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The local copy of the archive '{0}' does not exist. Use the '{1}' option to specify a different path..
        /// </summary>
        internal static string ArchiveFileNotFound {
            get {
                return ResourceManager.GetString("ArchiveFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command '{0}' specifies path '{1}' but this file does not exist in the archive..
        /// </summary>
        internal static string CommandPathNotFound {
            get {
                return ResourceManager.GetString("CommandPathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for executable files.
        /// </summary>
        internal static string DetectingCandidates {
            get {
                return ResourceManager.GetString("DetectingCandidates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A manifest digest was calculated for an empty directory. Check that you have set the correct &quot;{0}&quot; value for the archive..
        /// </summary>
        internal static string EmptyImplementation {
            get {
                return ResourceManager.GetString("EmptyImplementation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application&apos;s entry point was not found.
        ///Try specifying it manually..
        /// </summary>
        internal static string EntryPointNotFound {
            get {
                return ResourceManager.GetString("EntryPointNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading &apos;{0}&apos; using Zero Install.
        /// </summary>
        internal static string FetchingExternal {
            get {
                return ResourceManager.GetString("FetchingExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; could not be found..
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected &apos;{0}&apos; as installation directory..
        /// </summary>
        internal static string InstallationDirDetected {
            get {
                return ResourceManager.GetString("InstallationDirDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No 32-bit %ProgramFiles% directory found..
        /// </summary>
        internal static string MissingProgramFiles32Bit {
            get {
                return ResourceManager.GetString("MissingProgramFiles32Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple new default programs were detected in the registry. Handling them all, but the last one may take precedence in  some cases..
        /// </summary>
        internal static string MultipleDefaultProgramsDetected {
            get {
                return ResourceManager.GetString("MultipleDefaultProgramsDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feed has multiple {0} elements. This is not supported here..
        /// </summary>
        internal static string MultipleFeedFor {
            get {
                return ResourceManager.GetString("MultipleFeedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple installation directories were detected. Choosing first by default..
        /// </summary>
        internal static string MultipleInstallationDirsDetected {
            get {
                return ResourceManager.GetString("MultipleInstallationDirsDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no implementation with the ID '{0}' and there are multiple local implementations to choose from..
        /// </summary>
        internal static string MultipleLocalImplementations {
            get {
                return ResourceManager.GetString("MultipleLocalImplementations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple new application registrations were detected in the registry. Choosing first by default..
        /// </summary>
        internal static string MultipleRegisteredAppsDetected {
            get {
                return ResourceManager.GetString("MultipleRegisteredAppsDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are multiple testing versions. Marking {0} of {1} implementations with version {2} as stable..
        /// </summary>
        internal static string MultipleTestingVersions {
            get {
                return ResourceManager.GetString("MultipleTestingVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are multiple implementations without a release date. Select a specific version instead..
        /// </summary>
        internal static string MultipleUnreleasedImplementations {
            get {
                return ResourceManager.GetString("MultipleUnreleasedImplementations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No implementation of version {0} is cached. Unable to calculate an additional digest..
        /// </summary>
        internal static string NoCachedImplementation {
            get {
                return ResourceManager.GetString("NoCachedImplementation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feed has no {0} element. Unable to use it as a local feed..
        /// </summary>
        internal static string NoFeedFor {
            get {
                return ResourceManager.GetString("NoFeedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feed contains no implementation with version {0}..
        /// </summary>
        internal static string NoImplementationWithVersion {
            get {
                return ResourceManager.GetString("NoImplementationWithVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feed contains no implementations..
        /// </summary>
        internal static string NoImplementations {
            get {
                return ResourceManager.GetString("NoImplementations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No installation directory was detected.
        ///Try specifying it manually..
        /// </summary>
        internal static string NoInstallationDirDetected {
            get {
                return ResourceManager.GetString("NoInstallationDirDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no implementation with the ID '{0}' and no local implementation to apply the archive to..
        /// </summary>
        internal static string NoLocalImplementation {
            get {
                return ResourceManager.GetString("NoLocalImplementation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No implementation is currently marked as testing..
        /// </summary>
        internal static string NoTestingImplementations {
            get {
                return ResourceManager.GetString("NoTestingImplementations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method is currently only available on Windows..
        /// </summary>
        internal static string OnlyAvailableOnWindows {
            get {
                return ResourceManager.GetString("OnlyAvailableOnWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The secret key is not in the user&apos;s keyring..
        /// </summary>
        internal static string SecretKeyNotInKeyring {
            get {
                return ResourceManager.GetString("SecretKeyNotInKeyring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size not determined yet..
        /// </summary>
        internal static string SizeMissing {
            get {
                return ResourceManager.GetString("SizeMissing", resourceCulture);
            }
        }
    }
}
