//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroInstall.Model.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZeroInstall.Model.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string must be in the form &quot;os-cpu&quot;..
        /// </summary>
        internal static string ArchitectureStringFormat {
            get {
                return ResourceManager.GetString("ArchitectureStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find command &apos;{0}&apos;..
        /// </summary>
        internal static string CommandNotFound {
            get {
                return ResourceManager.GetString("CommandNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading feed preferences for &apos;{0}&apos;. Reverting to default values..
        /// </summary>
        internal static string ErrorLoadingFeedPrefs {
            get {
                return ResourceManager.GetString("ErrorLoadingFeedPrefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading interface preferences for &apos;{0}&apos;. Reverting to default values..
        /// </summary>
        internal static string ErrorLoadingInterfacePrefs {
            get {
                return ResourceManager.GetString("ErrorLoadingInterfacePrefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find feed &apos;{0}&apos; in catalog..
        /// </summary>
        internal static string FeedNotInCatalog {
            get {
                return ResourceManager.GetString("FeedNotInCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found instead:.
        /// </summary>
        internal static string FoundInstead {
            get {
                return ResourceManager.GetString("FoundInstead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find implementation for interface &apos;{0}&apos; in the selection..
        /// </summary>
        internal static string ImplementationNotInSelection {
            get {
                return ResourceManager.GetString("ImplementationNotInSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid &apos;http(s):&apos; URI and is not a valid local path either..
        /// </summary>
        internal static string InvalidFeedUri {
            get {
                return ResourceManager.GetString("InvalidFeedUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid &apos;{0}&apos; attribute on &lt;{1}&gt; tag..
        /// </summary>
        internal static string InvalidXmlAttributeOnTag {
            get {
                return ResourceManager.GetString("InvalidXmlAttributeOnTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing &apos;{0}&apos; attribute on &lt;{1}&gt; tag..
        /// </summary>
        internal static string MissingXmlAttributeOnTag {
            get {
                return ResourceManager.GetString("MissingXmlAttributeOnTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing &lt;{0}&gt; tag on feed {1}..
        /// </summary>
        internal static string MissingXmlTagOnFeed {
            get {
                return ResourceManager.GetString("MissingXmlTagOnFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dot-separated list may only contain decimal numbers..
        /// </summary>
        internal static string MustBeDottedList {
            get {
                return ResourceManager.GetString("MustBeDottedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version number may only contain dot-separated decimals and modifier strings..
        /// </summary>
        internal static string MustBeValidVersionPart {
            get {
                return ResourceManager.GetString("MustBeValidVersionPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version number must begin with a list of dot-separated decimals..
        /// </summary>
        internal static string MustStartWithDottedList {
            get {
                return ResourceManager.GetString("MustStartWithDottedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No known digest method was specified..
        /// </summary>
        internal static string NoKnownDigestMethod {
            get {
                return ResourceManager.GetString("NoKnownDigestMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The relative path &apos;{0}&apos; could not be resolved. Only feeds saved as local files may contain relative paths..
        /// </summary>
        internal static string RelativePathUnresolvable {
            get {
                return ResourceManager.GetString("RelativePathUnresolvable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The relative URI &apos;{0}&apos; could not be resolved. Only feeds saved as local files may contain relative URIs..
        /// </summary>
        internal static string RelativeUriUnresolvable {
            get {
                return ResourceManager.GetString("RelativeUriUnresolvable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buggy implementation.
        /// </summary>
        internal static string SelectionCandidateNoteBuggy {
            get {
                return ResourceManager.GetString("SelectionCandidateNoteBuggy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not provide command &apos;{0}&apos;..
        /// </summary>
        internal static string SelectionCandidateNoteCommand {
            get {
                return ResourceManager.GetString("SelectionCandidateNoteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompatible operating system or CPU.
        /// </summary>
        internal static string SelectionCandidateNoteIncompatibleArchitecture {
            get {
                return ResourceManager.GetString("SelectionCandidateNoteIncompatibleArchitecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insecure implementation.
        /// </summary>
        internal static string SelectionCandidateNoteInsecure {
            get {
                return ResourceManager.GetString("SelectionCandidateNoteInsecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implementation not in cache (currently in off-line mode).
        /// </summary>
        internal static string SelectionCandidateNoteNotCached {
            get {
                return ResourceManager.GetString("SelectionCandidateNoteNotCached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-executable source implementation.
        /// </summary>
        internal static string SelectionCandidateNoteSource {
            get {
                return ResourceManager.GetString("SelectionCandidateNoteSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implementation version too old or too new.
        /// </summary>
        internal static string SelectionCandidateNoteVersionMismatch {
            get {
                return ResourceManager.GetString("SelectionCandidateNoteVersionMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should be a valid MIME type..
        /// </summary>
        internal static string ShouldBeMimeType {
            get {
                return ResourceManager.GetString("ShouldBeMimeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should be a safe ID. May only contain alphanumeric characters, dots (.), underscores (_), hyphens (-) and plus signs (+)..
        /// </summary>
        internal static string ShouldBeSafeID {
            get {
                return ResourceManager.GetString("ShouldBeSafeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recipe step &apos;{0}&apos; in the implementation &apos;{1}&apos; has an invalid implementation reference..
        /// </summary>
        internal static string UnableToResolveRecipeReference {
            get {
                return ResourceManager.GetString("UnableToResolveRecipeReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file extension &apos;{0}&apos; does not correspond to a known archive type..
        /// </summary>
        internal static string UnknownArchiveType {
            get {
                return ResourceManager.GetString("UnknownArchiveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown modifier..
        /// </summary>
        internal static string UnknownModifier {
            get {
                return ResourceManager.GetString("UnknownModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of version range must be exclusive. Use &apos;..!{0}&apos;, not &apos;..{0}&apos;..
        /// </summary>
        internal static string VersionRangeEndNotExclusive {
            get {
                return ResourceManager.GetString("VersionRangeEndNotExclusive", resourceCulture);
            }
        }
    }
}
