<Project Sdk="Microsoft.NET.Sdk">

  <!-- Project properties -->
  <PropertyGroup>
    <AssemblyName>ZeroInstall.DesktopIntegration</AssemblyName>
    <RootNamespace>ZeroInstall.DesktopIntegration</RootNamespace>
    <Description>Zero Install methods for integrating applications with desktop environments (creating menu entries, etc.).</Description>
    <PackageProjectUrl>https://dotnet.0install.net/namespace_zero_install_1_1_desktop_integration.html</PackageProjectUrl>
    <OutputPath>..\..\artifacts\$(Configuration)\</OutputPath>
    <SGenTypes>ZeroInstall.DesktopIntegration.AppList</SGenTypes>
  </PropertyGroup>
  <PropertyGroup Condition="'$(TargetFramework)'=='net8.0' Or '$(TargetFramework)'=='net9.0' Or '$(TargetFramework)'=='net10.0'">
    <Nullable>enable</Nullable>
    <EnableSingleFileAnalyzer>True</EnableSingleFileAnalyzer>
  </PropertyGroup>
  <Import Project="..\Resources.Designer.props" />
  <Import Project="..\XmlSerializer.Generator.props" />

  <!-- Global usings -->
  <ItemGroup>
    <Using Include="ZeroInstall.Model.Capabilities" />
    <Using Include="ZeroInstall.Store.Icons" />
    <Using Include="ZeroInstall.DesktopIntegration.Properties" />
  </ItemGroup>

  <!-- Dependencies -->
  <ItemGroup>
    <ProjectReference Include="..\Store\Store.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="securifybv.ShellLink" Version="0.1.0" />
    <PackageReference Include="SharpZipLib" Version="1.4.2" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)'=='net48'">
    <Reference Include="System.Net.Http" Pack="False" />
  </ItemGroup>

  <!-- Stub EXE templates (built but not referenced) -->
  <ItemGroup>
    <ProjectReference Include="..\Stub\Cli\Stub.Cli.csproj" ReferenceOutputAssembly="False" SkipGetTargetFrameworkProperties="True" GlobalPropertiesToRemove="TargetFramework" PrivateAssets="All" />
    <ProjectReference Include="..\Stub\Gui\Stub.Gui.csproj" ReferenceOutputAssembly="False" SkipGetTargetFrameworkProperties="True" GlobalPropertiesToRemove="TargetFramework" PrivateAssets="All" />
  </ItemGroup>

  <!-- Embedded resources -->
  <ItemGroup>
    <EmbeddedResource Include="..\Stub\bin\$(Configuration)\ZeroInstall.Stub.Cli.exe" LogicalName="ZeroInstall.DesktopIntegration.Windows.stub-cli.exe" Visible="False" />
    <EmbeddedResource Include="..\Stub\bin\$(Configuration)\ZeroInstall.Stub.Gui.exe" LogicalName="ZeroInstall.DesktopIntegration.Windows.stub-gui.exe" Visible="False" />
  </ItemGroup>

</Project>
