name: Build
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            build: src\build.ps1
            test: src\test.ps1
          - os: ubuntu-latest
            build: src/build.sh
            test: src/test.sh
          - os: macos-latest
            build: src/build.sh
            test: src/test.sh
    runs-on: ${{matrix.os}}
    timeout-minutes: 30

    steps:
      # Prepare
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          show-progress: false
      - uses: gittools/actions/gitversion/setup@v3.2.1
        with:
          versionSpec: '5.12.x'
      - uses: gittools/actions/gitversion/execute@v3.2.1
        id: gitversion

      # Build
      - name: Build
        run: ${{matrix.build}} ${{steps.gitversion.outputs.nuGetVersion}}${{github.ref_type != 'tag' && format('-{0}', steps.gitversion.outputs.shortSha) || ''}}
      - name: Test
        run: ${{matrix.test}}
        timeout-minutes: 15
      - name: Report test results
        if: always()
        uses: dorny/test-reporter@v3
        with:
          name: ${{runner.os}} - Test Report
          reporter: dotnet-trx
          path: src/UnitTests/TestResults/*.trx
      - name: Upload hang dumps
        if: failure() || cancelled()
        uses: actions/upload-artifact@v7
        with:
          name: ${{runner.os}}-hang-dumps
          path: |
            src/UnitTests/TestResults/**/*_hang.dmp
            src/UnitTests/TestResults/**/*_hang.log
          if-no-files-found: ignore
      - name: Build documentation
        if: runner.os == 'Windows'
        run: doc\build.ps1

      # Sign
      - name: Upload artifacts
        if: runner.os == 'Windows'
        id: artifacts
        uses: actions/upload-artifact@v7
        with:
          path: artifacts
      - name: Sign artifacts
        if: runner.os == 'Windows' && github.ref_type == 'tag'
        uses: signpath/github-action-submit-signing-request@v3
        with:
          api-token: ${{secrets.SIGNPATH_API_KEY}}
          organization-id: 0e70cf92-49a1-4427-a800-b6bc5b497936
          project-slug: dotnet
          signing-policy-slug: release-signing
          github-artifact-id: ${{steps.artifacts.outputs.artifact-id}}
          output-artifact-directory: artifacts

      # Package
      - uses: 0install/github-actions/0template@v1
        if: runner.os == 'Windows'
        id: feed
        with:
          template: 0install-dotnet.xml.template
          version: ${{steps.gitversion.outputs.legacySemVer}}
          github-release: ${{github.ref_type == 'tag'}}

      # Release
      - name: Get tag message
        if: runner.os == 'Windows' && github.ref_type == 'tag'
        id: tag_message
        run: |
          "message<<EOF" >> $env:GITHUB_OUTPUT
          git fetch -f origin tag ${{github.ref_name}}
          git tag --format="%(contents)" -l ${{github.ref_name}} >> $env:GITHUB_OUTPUT
          "EOF" >> $env:GITHUB_OUTPUT
      - name: Create GitHub Release
        if: runner.os == 'Windows' && github.ref_type == 'tag'
        uses: softprops/action-gh-release@v3
        with:
          body: |
            This release mainly serves as a dependency. For end-user releases, take a look at [0install-win](https://github.com/0install/0install-win).
            ## Changes
            ${{steps.tag_message.outputs.message}}
          files: |
            ${{steps.feed.outputs.feed}}
            ${{steps.feed.outputs.archive}}

      # Publish
      - name: Publish documentation
        if: runner.os == 'Windows' && github.ref_type == 'tag'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{github.token}}
          force_orphan: true
          publish_dir: artifacts/Documentation
          cname: dotnet.0install.net
      - name: Publish packages (GitHub)
        if: runner.os == 'Windows' && github.event_name == 'push' && !startsWith(github.ref_name, 'renovate/')
        run: dotnet nuget push artifacts\Release\*.nupkg --source https://nuget.pkg.github.com/${{github.repository_owner}}/index.json --api-key ${{github.token}} --no-symbols --skip-duplicate
      - name: Publish packages (NuGet.org)
        if: runner.os == 'Windows' && github.ref_type == 'tag'
        run: dotnet nuget push artifacts\Release\*.nupkg --source nuget.org --api-key ${{secrets.NUGET_API_KEY}}
      - uses: 0install/github-actions/0repo-submit@v1
        if: runner.os == 'Windows' && github.ref_type == 'tag'
        with:
          repository: 0install/apps
          feed-url: ${{steps.feed.outputs.feed}}
          token: ${{secrets.PERSONAL_TOKEN}}
