# Publish API documentation to GitHub Pages
name: Documentation
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download documentation
        run: |
          curl -sSfLO https://github.com/0install/0install-dotnet/releases/download/${{github.ref_name}}/docs.zip
          unzip -q docs.zip -d docs

      - name: Publish documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{github.token}}
          force_orphan: true
          publish_dir: docs
          cname: dotnet.0install.net
