# Generate and publish source documentation
name: Documentation
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Prepare
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: gittools/actions/gitversion/setup@v0.9.4
        with:
          versionSpec: 5.3.x
      - uses: gittools/actions/gitversion/execute@v0.9.4
        id: gitversion
      - uses: actions/cache@v2
        with:
          path: ~/.cache/0install.net
          key: 0install-${{hashFiles('**/build.sh')}}

      # Build
      - name: Build documentation (pre-release)
        if: steps.gitversion.outputs.preReleaseLabel != ''
        run: doc/build.sh ${{steps.gitversion.outputs.nuGetVersion}}-${{steps.gitversion.outputs.shortSha}}
      - name: Build documentation (release)
        if: steps.gitversion.outputs.preReleaseLabel == ''
        run: doc/build.sh ${{steps.gitversion.outputs.nuGetVersion}}

      # Publish
      - name: Publish documentation
        if: github.event_name == 'push' && steps.gitversion.outputs.preReleaseLabel == ''
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{github.token}}
          force_orphan: true
          publish_dir: artifacts/Documentation
          cname: dotnet.0install.net
