# Generate and publish source documentation
name: Documentation
on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Prepare
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: gittools/actions/gitversion/setup@v0.9.9
        with:
          versionSpec: '5.5.x'
      - uses: gittools/actions/gitversion/execute@v0.9.9
        id: gitversion
      - uses: actions/cache@v2
        with:
          path: |
            ~\AppData\Roaming\0install.net
            ~\AppData\Local\0install.net
            C:\ProgramData\0install.net
          key: 0install-${{hashFiles('**/build.ps1')}}

      # Build
      - name: Build documentation
        run: doc\build.ps1 ${{steps.gitversion.outputs.nuGetVersion}}

      # Publish
      - name: Publish documentation
        if: steps.gitversion.outputs.preReleaseLabel == ''
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{github.token}}
          force_orphan: true
          publish_dir: artifacts/Documentation
          cname: dotnet.0install.net
