name: Translate Upload
on:
  workflow_dispatch: {}
  push:
    branches: [master]
    paths: ['**/*.resx', '!**/*.*.resx'] # non-localized resource files

jobs:
  translate-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          show-progress: false

      - name: Transifex Push
        run: ./0install.sh run https://apps.0install.net/devel/transifex-cli.xml --token ${{secrets.TRANSIFEX_API_KEY}} push --source
